using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

namespace GisServer.Api.ArcGis;

/// <summary>
/// A cartographic style somebody wrote, checked before it is stored.
/// </summary>
/// <remarks>
/// <para>
/// <b>The generated style was always a placeholder.</b> Every polygon came out
/// the same blue in publication order, because choosing a colour depends on what
/// a layer means, what it sits on, and who is looking — none of which a server
/// knows. This is the type that lets somebody who does know say so.
/// </para>
/// <para>
/// <b>Validated on the way in, not on the way out.</b> A style is written once
/// and served thousands of times; checking at write is where the person who can
/// fix it is still holding it. It also means the serving path stays a read.
/// </para>
/// <para>
/// <b>The checks are the ones that fail silently otherwise.</b> A style with a
/// mistyped <c>source-layer</c> renders a blank map and reports nothing — the
/// client is behaving correctly, the tiles are correct, and there is no error
/// anywhere. That is the single most common authoring mistake and the one worth
/// a round trip. The rest are security: a style is a document this server hands
/// to a browser, and a browser will fetch whatever URLs are in it.
/// </para>
/// </remarks>
public static class StyleDocument
{
    /// <summary>The largest style this server will store.</summary>
    /// <remarks>
    /// A megabyte. Real styles are tens of kilobytes, so this is a bound on
    /// abuse rather than a limit anybody meets — a style that reaches it was
    /// generated by accident, and the column has a matching constraint so the
    /// bound cannot be bypassed by a second writer.
    /// </remarks>
    public const int MaximumBytes = 1024 * 1024;

    /// <summary>The style spec version this server understands.</summary>
    public const int Version = 8;

    /// <summary>
    /// Checks a style against the service it is for.
    /// </summary>
    /// <param name="json">The document as it was sent.</param>
    /// <param name="sourceLayers">The layer names the service actually has.</param>
    /// <param name="error">Why it was refused, naming what to change.</param>
    /// <returns>True when it is safe to store.</returns>
    public static bool TryValidate(
        string? json, IReadOnlyCollection<string> sourceLayers, out string? error)
    {
        ArgumentNullException.ThrowIfNull(sourceLayers);

        error = null;

        if (string.IsNullOrWhiteSpace(json))
        {
            error = "A style document is required. To go back to the generated default, "
                  + "DELETE this resource rather than sending an empty one.";
            return false;
        }

        if (System.Text.Encoding.UTF8.GetByteCount(json) > MaximumBytes)
        {
            error = $"A style may be at most {MaximumBytes / 1024} KB. Real styles are tens of "
                  + "kilobytes; one this size is usually a generated file sent by mistake.";
            return false;
        }

        JsonDocument document;

        try
        {
            // Depth is bounded by the reader rather than by us. A style is
            // nested a handful of levels; anything approaching the default 64
            // is not a style, and a parser is a decompressor too.
            document = JsonDocument.Parse(json, new JsonDocumentOptions { MaxDepth = 32 });
        }
        catch (JsonException e)
        {
            error = $"The style is not valid JSON: {e.Message}";
            return false;
        }

        using (document)
        {
            return Check(document.RootElement, sourceLayers, out error);
        }
    }

    private static bool Check(
        JsonElement root, IReadOnlyCollection<string> sourceLayers, out string? error)
    {
        error = null;

        if (root.ValueKind != JsonValueKind.Object)
        {
            error = "A style is a JSON object.";
            return false;
        }

        if (!root.TryGetProperty("version", out JsonElement version)
            || version.ValueKind != JsonValueKind.Number
            || !version.TryGetInt32(out int number)
            || number != Version)
        {
            error = $"A style must declare \"version\": {Version}. That is the only style "
                  + "specification version this server serves, and a client reads the version "
                  + "before anything else.";
            return false;
        }

        if (!root.TryGetProperty("layers", out JsonElement layers)
            || layers.ValueKind != JsonValueKind.Array)
        {
            error = "A style must have a \"layers\" array. An empty one is allowed and draws "
                  + "nothing, which is different from having none.";
            return false;
        }

        if (!Urls(root, out error))
        {
            return false;
        }

        return Layers(layers, sourceLayers, out error);
    }

    /// <summary>
    /// Nothing in the document may point off this server.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Two reasons, and the second is the one people miss.</b> Q-15 requires
    /// air-gapped operation, so a style fetching tiles or fonts from the
    /// internet is broken in the deployments this product is for.
    /// </para>
    /// <para>
    /// <b>And a style is a document we hand to a browser.</b> Whatever URLs it
    /// contains, that browser fetches — with the user's network position. A
    /// style stored by one publisher and viewed by everybody else in the
    /// organisation is a way to make their browsers reach an address of the
    /// publisher's choosing, and to learn who looked at the map and when.
    /// Relative URLs only, checked rather than rewritten.
    /// </para>
    /// </remarks>
    private static bool Urls(JsonElement root, out string? error)
    {
        error = null;

        foreach (string key in (string[])["glyphs", "sprite"])
        {
            if (root.TryGetProperty(key, out JsonElement value)
                && value.ValueKind == JsonValueKind.String
                && !IsLocal(value.GetString()))
            {
                error = $"\"{key}\" must be a relative URL on this server. A style is fetched by "
                      + "a browser, so an absolute one sends every viewer to somebody else's "
                      + "host — and it cannot work in an air-gapped deployment.";
                return false;
            }
        }

        if (!root.TryGetProperty("sources", out JsonElement sources)
            || sources.ValueKind != JsonValueKind.Object)
        {
            return true;
        }

        foreach (JsonProperty source in sources.EnumerateObject())
        {
            if (source.Value.ValueKind != JsonValueKind.Object)
            {
                continue;
            }

            foreach (string key in (string[])["url", "tiles", "data"])
            {
                if (!source.Value.TryGetProperty(key, out JsonElement value))
                {
                    continue;
                }

                foreach (string? candidate in value.ValueKind == JsonValueKind.Array
                             ? value.EnumerateArray().Select(v => v.GetString())
                             : [value.GetString()])
                {
                    if (!IsLocal(candidate))
                    {
                        error = $"Source '{source.Name}' points at '{candidate}'. Sources must be "
                              + "relative URLs on this server: a style is fetched by a browser, "
                              + "and an absolute URL sends every viewer of this map to another "
                              + "host.";
                        return false;
                    }
                }
            }
        }

        return true;
    }

    /// <summary>
    /// Whether a URL stays on this server.
    /// </summary>
    /// <remarks>
    /// <b>Refuses a scheme, a protocol-relative URL and a root-relative one.</b>
    /// The first two leave the host. The third — <c>/anything</c> — stays on the
    /// host but leaves the service, and a style is served from a path whose
    /// meaning is relative to it; allowing an absolute path would let a style
    /// for one service address another's resources, which is a sharing boundary
    /// expressed as a URL.
    /// </remarks>
    private static bool IsLocal(string? url) =>
        !string.IsNullOrWhiteSpace(url)
        && !url.StartsWith("//", StringComparison.Ordinal)
        && !url.StartsWith('/')
        && !url.Contains("://", StringComparison.Ordinal)
        && !url.Contains(':', StringComparison.Ordinal);


    /// <summary>
    /// Whether a layer draws an icon this server cannot supply.
    /// </summary>
    /// <remarks>
    /// <b>Refused rather than allowed to fail quietly.</b> The sprite sheet
    /// exists and is empty (ADR-027 condition 5), so an <c>icon-image</c>
    /// renders nothing, logs nothing, and looks like a data problem. Telling the
    /// author at the moment they store the style is the whole point of
    /// validating here — and this check disappears the day sprites can be
    /// uploaded, which is the trigger written into the condition.
    /// </remarks>
    private static bool UsesAnIcon(JsonElement layer) =>
        layer.TryGetProperty("layout", out JsonElement layout)
        && layout.ValueKind == JsonValueKind.Object
        && layout.TryGetProperty("icon-image", out JsonElement icon)
        && icon.ValueKind is not JsonValueKind.Null;

    /// <summary>
    /// Every layer must name a source layer that exists.
    /// </summary>
    /// <remarks>
    /// <b>The check that pays for this whole type.</b> A mistyped
    /// <c>source-layer</c> produces a map with nothing on it, no error in the
    /// client, no error in the server, and correct tiles — so the author looks
    /// for the bug everywhere except the one line that has it.
    /// </remarks>
    private static bool Layers(
        JsonElement layers, IReadOnlyCollection<string> sourceLayers, out string? error)
    {
        error = null;

        int index = -1;

        foreach (JsonElement layer in layers.EnumerateArray())
        {
            index++;

            if (layer.ValueKind != JsonValueKind.Object)
            {
                error = $"Layer {index} is not an object.";
                return false;
            }

            if (!layer.TryGetProperty("id", out JsonElement id)
                || id.ValueKind != JsonValueKind.String
                || string.IsNullOrWhiteSpace(id.GetString()))
            {
                error = $"Layer {index} needs an \"id\". A client keys everything off it, "
                      + "including which layer an error is about.";
                return false;
            }

            if (!layer.TryGetProperty("source-layer", out JsonElement sourceLayer)
                || sourceLayer.ValueKind != JsonValueKind.String)
            {
                // Background layers legitimately have no source.
                if (layer.TryGetProperty("type", out JsonElement type)
                    && type.ValueKind == JsonValueKind.String
                    && string.Equals(type.GetString(), "background", StringComparison.Ordinal))
                {
                    continue;
                }

                error = $"Layer '{id.GetString()}' has no \"source-layer\". Only a background "
                      + "layer may leave it out.";
                return false;
            }

            if (UsesAnIcon(layer))
            {
                error = $"Layer '{id.GetString()}' sets \"icon-image\", and this server has no "
                      + "sprite sheet to draw it from — the one it serves is deliberately empty "
                      + "because there is no way to upload icons yet (ADR-027). The layer would "
                      + "render nothing and report nothing, so it is refused here instead. Use a "
                      + "circle or a text symbol until sprites exist.";
                return false;
            }

            string named = sourceLayer.GetString()!;

            if (!sourceLayers.Contains(named, StringComparer.Ordinal))
            {
                error = $"Layer '{id.GetString()}' draws source-layer '{named}', which this "
                      + $"service does not have. It has: {string.Join(", ", sourceLayers)}. A "
                      + "style naming a layer that is not there renders an empty map and reports "
                      + "nothing, which is why this is refused rather than stored.";

                return false;
            }
        }

        return true;
    }
}
