using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Graticula.Geometries;

namespace Graticula.Cartography;

/// <summary>
/// The canonical symbology document, and the two conversions either side of it.
/// </summary>
/// <remarks>
/// <para>
/// <b>ADR-033 §5a: the canonical document is a MapLibre style, stored per layer.</b>
/// This class is the whole of the conversion the decision rests on — a caller may
/// author in MapLibre or paste an Esri <c>drawingInfo</c>, and the feature face has
/// to be handed a <c>drawingInfo</c> whichever they did.
/// </para>
/// <para>
/// <b>Every conversion reports what it lost, and that is §7's second condition
/// rather than a nicety.</b> The risk this decision accepted is silent
/// approximation: a style with a zoom-interpolated width has no Esri equivalent, and
/// a server that quietly emits the width at zoom 0 has told a client something
/// untrue about the map. So each direction returns a list of sentences, each naming
/// the property and what happened to it, and the write endpoint returns them to
/// whoever wrote the style.
/// </para>
/// <para>
/// <b>Three renderer families and no more</b> — <c>simple</c>, <c>uniqueValue</c>,
/// <c>classBreaks</c>, with <c>esriSFS</c>, <c>esriSLS</c> and <c>esriSMS</c> symbols
/// (§5e). CIM is not claimed. A-077 is the assumption that this covers the
/// overwhelming majority of published layers, and it is `UNVALIDATED`: what is
/// written here is the bet, not evidence for it.
/// </para>
/// <para>
/// <b>Not a symbology model.</b> §2D rejected inventing one and this is not it
/// arriving by the back door: there is no intermediate type here that both formats
/// are projected onto. The canonical MapLibre document *is* the model, and this
/// reads and writes it directly.
/// </para>
/// </remarks>
public static class SymbologyConversion
{
    /// <summary>
    /// The largest canonical document that may be stored, in characters.
    /// </summary>
    /// <remarks>
    /// <b>Mirrored by a check constraint in migration 23, which is the one that
    /// counts.</b> ADR-033 §7's fifth condition says so directly, and migration 14's
    /// comment says why: a bound that lives only in the application is a bound the
    /// next writer bypasses. This constant exists so the refusal can name a number a
    /// caller can act on rather than surfacing as a constraint violation.
    /// </remarks>
    public const int MaximumCharacters = 262_144;

    /// <summary>Points to pixels. A point is three quarters of a pixel at 96 DPI.</summary>
    private const double PointsToPixels = 1 / 0.75;

    /// <summary>
    /// Reads either kind of document and returns the canonical form.
    /// </summary>
    /// <param name="document">A MapLibre style or an Esri <c>drawingInfo</c>.</param>
    /// <param name="geometry">
    /// The layer's geometry, which decides what a paint property means. A style
    /// authored for the wrong geometry is a refusal rather than a loss.
    /// </param>
    /// <returns>The canonical document, what was lost, and which shape came in.</returns>
    /// <exception cref="SymbologyException">The document is not usable.</exception>
    public static SymbologyWrite Read(string document, GeometryKind geometry)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(document);

        if (document.Length > MaximumCharacters)
        {
            throw new SymbologyException(
                $"A symbology document may be at most {MaximumCharacters:N0} characters; this one "
                + $"is {document.Length:N0}. A style that large was generated by accident — real "
                + "ones are tens of kilobytes.");
        }

        JsonNode root;

        try
        {
            root = JsonNode.Parse(document)
                ?? throw new SymbologyException("The document is null.");
        }
        catch (JsonException e)
        {
            throw new SymbologyException($"The document is not JSON: {e.Message}", e);
        }

        if (root is not JsonObject body)
        {
            throw new SymbologyException(
                "The document must be an object — either a MapLibre style with a `layers` array, "
                + "or an Esri drawingInfo with a `renderer`.");
        }

        // <b>Told apart by what they carry, not by a flag the caller sets.</b> A
        // drawingInfo has a renderer and a MapLibre style has layers; neither has the
        // other's key, so asking is unambiguous and a caller never has to declare
        // which format they pasted.
        if (body.ContainsKey("renderer"))
        {
            List<string> losses = new();
            JsonObject layers = FromDrawingInfo(body, geometry, losses);

            return new SymbologyWrite(Serialise(layers), losses, "drawingInfo");
        }

        if (body.ContainsKey("layers"))
        {
            List<string> losses = new();
            JsonObject normalised = Normalise(body, geometry, losses);

            return new SymbologyWrite(Serialise(normalised), losses, "MapLibre");
        }

        throw new SymbologyException(
            "The document has neither a `layers` array nor a `renderer`, so it is neither a "
            + "MapLibre style nor an Esri drawingInfo.");
    }

    /// <summary>
    /// Derives the Esri feature face from a canonical document.
    /// </summary>
    /// <param name="canonical">A stored canonical document.</param>
    /// <param name="layerName">The layer, for the renderer's label.</param>
    /// <param name="geometry">Its geometry, which decides the symbol family.</param>
    /// <returns>A <c>drawingInfo</c> ready to serialise, and what it could not carry.</returns>
    public static DerivedDrawingInfo ToDrawingInfo(
        string canonical, string layerName, GeometryKind geometry)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(canonical);
        ArgumentException.ThrowIfNullOrWhiteSpace(layerName);

        List<string> losses = new();

        JsonObject style = JsonNode.Parse(canonical) as JsonObject
            ?? throw new SymbologyException("The stored canonical document is not an object.");

        string wanted = MapLibreTypeFor(geometry);
        JsonArray layers = style["layers"] as JsonArray ?? new JsonArray();

        List<JsonObject> painting = layers
            .OfType<JsonObject>()
            .Where(l => string.Equals(Text(l["type"]), wanted, StringComparison.Ordinal))
            .ToList();

        // <b>Labels are named as lost rather than skipped.</b> A style with a symbol
        // layer is a style with labels, and ADR-033 §5g leaves labelling for later —
        // so the honest report is that this face carries none, not silence.
        if (layers.OfType<JsonObject>().Any(l =>
                string.Equals(Text(l["type"]), "symbol", StringComparison.Ordinal)))
        {
            losses.Add(
                "The style has a `symbol` layer, so it labels features. This face carries no "
                + "labelling: `labelingInfo` is null. ADR-033 §5g leaves labelling for later.");
        }

        if (painting.Count == 0)
        {
            throw new SymbologyException(
                $"The canonical document has no `{wanted}` layer, so there is nothing to draw a "
                + $"{geometry} layer with.");
        }

        if (painting.Count > 1)
        {
            losses.Add(
                $"The style has {painting.Count} `{wanted}` layers and an Esri renderer is one "
                + "symbol set. The first is used; the rest are drawn by the tile face only.");
        }

        JsonObject layer = painting[0];
        JsonObject paint = layer["paint"] as JsonObject ?? new JsonObject();

        if (layer["filter"] is not null)
        {
            losses.Add(
                "The layer carries a `filter`. Esri renderers select a symbol by value and cannot "
                + "hide a feature, so every feature is drawn on this face.");
        }

        object renderer = wanted switch
        {
            "fill" => FillRenderer(paint, layerName, losses),
            "line" => LineRenderer(paint, layerName, losses),
            _ => CircleRenderer(paint, layerName, losses),
        };

        JsonNode drawingInfo = JsonSerializer.SerializeToNode(new
        {
            renderer,

            // Zero, and the opacity is in each symbol's alpha instead. Both are
            // honoured and applying both multiplies them — see the generated writer,
            // which made the same choice for the same reason.
            transparency = 0,
            labelingInfo = (object?)null,
        })!;

        return new DerivedDrawingInfo(drawingInfo, losses);
    }

    // ------------------------------------------------------------------ MapLibre in

    /// <summary>
    /// Keeps the authored parts of a style and regenerates nothing.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>ADR-033 §5c: <c>sources</c>, <c>sprite</c> and <c>glyphs</c> are generated
    /// on read and never stored.</b> A stored absolute URL is a fact with an expiry
    /// date — it names a host, a scheme and a port that a deployment moved away from,
    /// and it is served to clients long after it stopped resolving.
    /// </para>
    /// <para>
    /// <b>So this refuses an absolute URL anywhere in the document, not only in the
    /// three blocks it strips.</b> §7's fourth condition is a rule about the stored
    /// form, and stripping the obvious places would leave <c>fill-pattern</c>,
    /// <c>icon-image</c> and any future property free to carry one. Checking every
    /// string is the only version of the rule that does not decay.
    /// </para>
    /// </remarks>
    private static JsonObject Normalise(JsonObject style, GeometryKind geometry, List<string> losses)
    {
        JsonArray layers = style["layers"] as JsonArray
            ?? throw new SymbologyException("`layers` must be an array.");

        if (layers.Count == 0)
        {
            throw new SymbologyException(
                "`layers` is empty, so this style draws nothing. Remove the symbology instead — a "
                + "layer with none gets the generated appearance, which is a real answer.");
        }

        foreach (string block in new[] { "sources", "sprite", "glyphs" })
        {
            if (style.ContainsKey(block))
            {
                losses.Add(
                    $"`{block}` was not stored. It is generated per request from the host that "
                    + "asked, so a stored one would be served after the deployment moved "
                    + "(ADR-033 §5c).");
            }
        }

        JsonArray kept = new();

        foreach (JsonNode? node in layers)
        {
            if (node is not JsonObject source)
            {
                throw new SymbologyException("Every entry in `layers` must be an object.");
            }

            string type = Text(source["type"])
                ?? throw new SymbologyException("Every layer needs a `type`.");

            if (type is not ("fill" or "line" or "circle" or "symbol"))
            {
                losses.Add(
                    $"A layer of type `{type}` was not stored. This server stores `fill`, `line`, "
                    + "`circle` and `symbol` layers, which are what its two faces can draw.");

                continue;
            }

            JsonObject layer = new()
            {
                ["id"] = Text(source["id"]) ?? $"{type}-{kept.Count}",
                ["type"] = type,
            };

            // `source` and `source-layer` are regenerated with the sources block —
            // a canonical document does not know which service will serve it.
            foreach (string property in new[] { "paint", "layout", "filter", "minzoom", "maxzoom" })
            {
                if (source[property] is { } value)
                {
                    layer[property] = value.DeepClone();
                }
            }

            kept.Add(layer);
        }

        if (kept.Count == 0)
        {
            throw new SymbologyException(
                "None of the style's layers is one this server can draw with.");
        }

        JsonObject canonical = new()
        {
            ["version"] = 8,
            ["layers"] = kept,
        };

        RefuseAbsoluteUrls(canonical);

        string wanted = MapLibreTypeFor(geometry);

        if (!kept.OfType<JsonObject>().Any(l =>
                string.Equals(Text(l["type"]), wanted, StringComparison.Ordinal)))
        {
            throw new SymbologyException(
                $"This is a {geometry} layer, so it needs a `{wanted}` layer to be drawn with; the "
                + "style has none. A style authored for another geometry is refused rather than "
                + "stored, because a stored one would render as nothing and look like a fault in "
                + "the data.");
        }

        return canonical;
    }

    /// <summary>Throws if any string anywhere in the document is an absolute URL.</summary>
    private static void RefuseAbsoluteUrls(JsonNode node)
    {
        switch (node)
        {
            case JsonObject o:
                foreach (KeyValuePair<string, JsonNode?> pair in o)
                {
                    if (pair.Value is not null)
                    {
                        RefuseAbsoluteUrls(pair.Value);
                    }
                }

                break;

            case JsonArray a:
                foreach (JsonNode? item in a)
                {
                    if (item is not null)
                    {
                        RefuseAbsoluteUrls(item);
                    }
                }

                break;

            case JsonValue v when v.TryGetValue(out string? text) && IsAbsolute(text):
                throw new SymbologyException(
                    $"'{text}' is an absolute URL, and a canonical document never stores one "
                    + "(ADR-033 §5c). Sources, sprites and glyph ranges are generated per request "
                    + "from the host that asked; a stored URL outlives the deployment that wrote "
                    + "it and is then served to clients as though it still resolved.");
        }

        static bool IsAbsolute(string? text) =>
            text is not null
            && (text.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("https://", StringComparison.OrdinalIgnoreCase)
                || text.StartsWith("//", StringComparison.Ordinal)
                || text.StartsWith("mapbox://", StringComparison.OrdinalIgnoreCase));
    }

    // --------------------------------------------------------------- drawingInfo in

    private static JsonObject FromDrawingInfo(
        JsonObject drawingInfo, GeometryKind geometry, List<string> losses)
    {
        if (drawingInfo["renderer"] is not JsonObject renderer)
        {
            throw new SymbologyException("`renderer` must be an object.");
        }

        string type = Text(renderer["type"])
            ?? throw new SymbologyException("The renderer needs a `type`.");

        if (drawingInfo["labelingInfo"] is JsonArray { Count: > 0 })
        {
            losses.Add(
                "`labelingInfo` was not converted. Labelling needs glyph ranges and a text layer, "
                + "which ADR-033 §5g leaves for later.");
        }

        // <b>Layer-level transparency is folded into the alpha channel.</b> An Esri
        // drawingInfo can express opacity twice — here and in each symbol's colour —
        // and a reader that carried both would multiply them, which is the 45%
        // becoming 20% fault the generated writer already avoids.
        double layerOpacity = 1;

        if (Number(drawingInfo["transparency"]) is { } transparency && transparency > 0)
        {
            layerOpacity = Math.Clamp(1 - (transparency / 100), 0, 1);
        }

        string maplibreType = MapLibreTypeFor(geometry);

        JsonObject paint = type switch
        {
            "simple" => SimplePaint(renderer, maplibreType, layerOpacity, losses),
            "uniqueValue" => UniqueValuePaint(renderer, maplibreType, layerOpacity, losses),
            "classBreaks" => ClassBreaksPaint(renderer, maplibreType, layerOpacity, losses),
            _ => throw new SymbologyException(
                $"`{type}` is not a renderer this server converts. ADR-033 §5e accepts `simple`, "
                + "`uniqueValue` and `classBreaks`; anything else — a dot density, a dictionary, a "
                + "CIM renderer — has no MapLibre equivalent that would survive being guessed at."),
        };

        JsonObject canonical = new()
        {
            ["version"] = 8,
            ["layers"] = new JsonArray
            {
                new JsonObject
                {
                    ["id"] = $"{maplibreType}-0",
                    ["type"] = maplibreType,
                    ["paint"] = paint,
                },
            },
        };

        RefuseAbsoluteUrls(canonical);
        return canonical;
    }

    private static JsonObject SimplePaint(
        JsonObject renderer, string type, double layerOpacity, List<string> losses)
    {
        if (renderer["symbol"] is not JsonObject symbol)
        {
            throw new SymbologyException("A `simple` renderer needs a `symbol`.");
        }

        return PaintFor(type, symbol, layerOpacity, losses);
    }

    private static JsonObject UniqueValuePaint(
        JsonObject renderer, string type, double layerOpacity, List<string> losses)
    {
        string field = Text(renderer["field1"])
            ?? throw new SymbologyException("A `uniqueValue` renderer needs `field1`.");

        foreach (string extra in new[] { "field2", "field3" })
        {
            if (Text(renderer[extra]) is { Length: > 0 })
            {
                losses.Add(
                    $"`{extra}` was not converted. A compound unique-value renderer joins fields "
                    + "with a delimiter, and this server matches on one field.");
            }
        }

        JsonArray infos = renderer["uniqueValueInfos"] as JsonArray
            ?? throw new SymbologyException("A `uniqueValue` renderer needs `uniqueValueInfos`.");

        // ["match", ["get", field], v1, colour1, v2, colour2, ..., fallback]
        JsonArray match = new() { "match", new JsonArray { "get", field } };

        string? fallback = null;
        JsonObject? shape = null;

        foreach (JsonNode? node in infos)
        {
            if (node is not JsonObject info || info["symbol"] is not JsonObject symbol)
            {
                continue;
            }

            shape ??= symbol;
            WarnOnDifferingShape(shape, symbol, losses);

            string value = Text(info["value"]) ?? string.Empty;
            match.Add(value);
            match.Add(Rgba(symbol, layerOpacity));
        }

        if (renderer["defaultSymbol"] is JsonObject defaultSymbol)
        {
            shape ??= defaultSymbol;
            fallback = Rgba(defaultSymbol, layerOpacity);
        }

        if (match.Count <= 2)
        {
            throw new SymbologyException(
                "The `uniqueValue` renderer has no usable `uniqueValueInfos`.");
        }

        // MapLibre's `match` requires a fallback. Esri's `defaultSymbol` is optional,
        // so an absent one becomes transparent — and that is said out loud, because a
        // feature drawn in nothing looks identical to a feature that is missing.
        if (fallback is null)
        {
            fallback = "rgba(0,0,0,0)";
            losses.Add(
                "The renderer has no `defaultSymbol`, so a value not in the list is drawn "
                + "transparent on the tile face. MapLibre's `match` requires a fallback and there "
                + "is nothing honest to invent.");
        }

        match.Add(fallback);

        JsonObject paint = PaintFor(type, shape!, layerOpacity, losses);
        paint[ColourProperty(type)] = match;
        return paint;
    }

    private static JsonObject ClassBreaksPaint(
        JsonObject renderer, string type, double layerOpacity, List<string> losses)
    {
        string field = Text(renderer["field"])
            ?? throw new SymbologyException("A `classBreaks` renderer needs a `field`.");

        if (Text(renderer["normalizationType"]) is { Length: > 0 } normalisation)
        {
            losses.Add(
                $"`normalizationType` ({normalisation}) was not converted. The breaks are applied "
                + "to the field's raw value, so a normalised renderer will classify differently "
                + "here than in ArcGIS.");
        }

        JsonArray infos = renderer["classBreakInfos"] as JsonArray
            ?? throw new SymbologyException("A `classBreaks` renderer needs `classBreakInfos`.");

        List<JsonObject> breaks = infos.OfType<JsonObject>()
            .Where(i => i["symbol"] is JsonObject)
            .OrderBy(i => Number(i["classMaxValue"]) ?? double.MaxValue)
            .ToList();

        if (breaks.Count == 0)
        {
            throw new SymbologyException(
                "The `classBreaks` renderer has no usable `classBreakInfos`.");
        }

        JsonObject shape = (JsonObject)breaks[0]["symbol"]!;

        // ["step", ["get", field], colour0, break1, colour1, ...] — the first colour
        // is below the first break, so the last classMaxValue is never a stop.
        JsonArray step = new()
        {
            "step",
            new JsonArray { "get", field },
            Rgba((JsonObject)breaks[0]["symbol"]!, layerOpacity),
        };

        for (int i = 1; i < breaks.Count; i++)
        {
            JsonObject symbol = (JsonObject)breaks[i]["symbol"]!;
            WarnOnDifferingShape(shape, symbol, losses);

            double bound = Number(breaks[i - 1]["classMaxValue"])
                ?? throw new SymbologyException("Every class break needs a `classMaxValue`.");

            step.Add(bound);
            step.Add(Rgba(symbol, layerOpacity));
        }

        JsonObject paint = PaintFor(type, shape, layerOpacity, losses);
        paint[ColourProperty(type)] = step;
        return paint;
    }

    /// <summary>
    /// Notes when classes differ in more than colour.
    /// </summary>
    /// <remarks>
    /// A classified renderer whose classes differ in size, outline or marker shape is
    /// a renderer this conversion flattens: the tile face varies the colour and takes
    /// the rest from the first class. Said rather than approximated, because a map
    /// whose graduated symbol sizes have all become one size looks correct.
    /// </remarks>
    private static void WarnOnDifferingShape(JsonObject first, JsonObject other, List<string> losses)
    {
        const string note =
            "Classes differ in more than colour (size, outline or marker style). The tile face "
            + "varies colour by class and takes the rest of the symbol from the first class.";

        if (losses.Contains(note))
        {
            return;
        }

        bool same =
            Number(first["size"]) == Number(other["size"])
            && Number(first["width"]) == Number(other["width"])
            && string.Equals(Text(first["style"]), Text(other["style"]), StringComparison.Ordinal);

        if (!same)
        {
            losses.Add(note);
        }
    }

    /// <summary>Builds the paint block for one Esri symbol.</summary>
    private static JsonObject PaintFor(
        string type, JsonObject symbol, double layerOpacity, List<string> losses)
    {
        string style = Text(symbol["style"]) ?? string.Empty;
        JsonObject paint = new();

        switch (type)
        {
            case "fill":
                paint["fill-color"] = Rgba(symbol, layerOpacity);

                if (symbol["outline"] is JsonObject outline)
                {
                    paint["fill-outline-color"] = Rgba(outline, 1);

                    if (Number(outline["width"]) is { } width && Math.Abs(width - 1) > 0.001)
                    {
                        losses.Add(
                            $"The fill's outline is {width} points wide. MapLibre's "
                            + "`fill-outline-color` is always one pixel; a wider outline needs its "
                            + "own `line` layer, which this conversion does not invent.");
                    }
                }

                if (!string.Equals(style, "esriSFSSolid", StringComparison.Ordinal)
                    && style.Length > 0)
                {
                    losses.Add(
                        $"The fill style `{style}` was converted to a solid fill. A hatch or a "
                        + "picture fill needs a sprite image, and ADR-027's sprite sheet holds "
                        + "none for it.");
                }

                break;

            case "line":
                paint["line-color"] = Rgba(symbol, layerOpacity);

                if (Number(symbol["width"]) is { } lineWidth)
                {
                    paint["line-width"] = Round(lineWidth * PointsToPixels);
                }

                if (DashFor(style) is { } dashes)
                {
                    paint["line-dasharray"] = dashes;
                }
                else if (!string.Equals(style, "esriSLSSolid", StringComparison.Ordinal)
                    && style.Length > 0)
                {
                    losses.Add(
                        $"The line style `{style}` was converted to a solid line. It has no dash "
                        + "pattern this server knows.");
                }

                break;

            default:
                paint["circle-color"] = Rgba(symbol, layerOpacity);

                if (Number(symbol["size"]) is { } size)
                {
                    // An Esri marker size is a diameter in points; a MapLibre radius
                    // is half of it, in pixels.
                    paint["circle-radius"] = Round(size * PointsToPixels / 2);
                }

                if (symbol["outline"] is JsonObject markerOutline)
                {
                    paint["circle-stroke-color"] = Rgba(markerOutline, 1);

                    if (Number(markerOutline["width"]) is { } strokeWidth)
                    {
                        paint["circle-stroke-width"] = Round(strokeWidth * PointsToPixels);
                    }
                }

                if (!string.Equals(style, "esriSMSCircle", StringComparison.Ordinal)
                    && style.Length > 0)
                {
                    losses.Add(
                        $"The marker style `{style}` was converted to a circle. A square, diamond "
                        + "or cross marker needs a sprite image, and ADR-027's sprite sheet holds "
                        + "none for it.");
                }

                if (Number(symbol["angle"]) is { } angle && Math.Abs(angle) > 0.001)
                {
                    losses.Add(
                        $"The marker's `angle` ({angle}°) was not converted. A rotated circle is "
                        + "the same circle, so nothing is lost visually until the marker is a "
                        + "sprite.");
                }

                if ((Number(symbol["xoffset"]) ?? 0) != 0 || (Number(symbol["yoffset"]) ?? 0) != 0)
                {
                    losses.Add(
                        "The marker's offset was not converted. `circle-translate` exists and "
                        + "means something subtly different, so this conversion declines to guess.");
                }

                break;
        }

        return paint;
    }

    /// <summary>The dash patterns worth mapping, in line widths.</summary>
    private static JsonArray? DashFor(string style) => style switch
    {
        "esriSLSDash" => new JsonArray { 4, 3 },
        "esriSLSDot" => new JsonArray { 1, 3 },
        "esriSLSDashDot" => new JsonArray { 4, 3, 1, 3 },
        "esriSLSDashDotDot" => new JsonArray { 4, 3, 1, 3, 1, 3 },
        _ => null,
    };

    // -------------------------------------------------------------- drawingInfo out

    private static object FillRenderer(JsonObject paint, string layerName, List<string> losses)
    {
        JsonNode? colour = paint["fill-color"];
        double opacity = Number(paint["fill-opacity"]) ?? 1;

        int[]? outline = paint["fill-outline-color"] is { } line
            ? Colour(Hex(Constant(line, "fill-outline-color", losses), "#000000"), 1)
            : null;

        NoteZoomDependence(paint, losses);

        object Symbol(string hex, double alpha) => new
        {
            type = "esriSFS",
            style = "esriSFSSolid",
            color = Colour(hex, alpha),
            outline = outline is null
                ? null
                : (object)new
                {
                    type = "esriSLS",
                    style = "esriSLSSolid",
                    color = outline,
                    width = 1,
                },
        };

        return Classified(colour, opacity, layerName, Symbol, losses, "fill-color");
    }

    private static object LineRenderer(JsonObject paint, string layerName, List<string> losses)
    {
        JsonNode? colour = paint["line-color"];
        double opacity = Number(paint["line-opacity"]) ?? 1;

        double width = Number(Constant(paint["line-width"], "line-width", losses)) is { } pixels
            ? Round(pixels * 0.75)
            : 1;

        string dashStyle = "esriSLSSolid";

        if (paint["line-dasharray"] is JsonArray dashes && dashes.Count > 0)
        {
            dashStyle = StyleForDash(dashes);

            if (string.Equals(dashStyle, "esriSLSSolid", StringComparison.Ordinal))
            {
                losses.Add(
                    "`line-dasharray` has no Esri equivalent pattern, so this face draws a solid "
                    + "line. The dash pattern survives on the tile face only.");
            }
        }

        NoteZoomDependence(paint, losses);

        object Symbol(string hex, double alpha) => new
        {
            type = "esriSLS",
            style = dashStyle,
            color = Colour(hex, alpha),
            width,
        };

        return Classified(colour, opacity, layerName, Symbol, losses, "line-color");
    }

    private static object CircleRenderer(JsonObject paint, string layerName, List<string> losses)
    {
        JsonNode? colour = paint["circle-color"];
        double opacity = Number(paint["circle-opacity"]) ?? 1;

        double size = Number(Constant(paint["circle-radius"], "circle-radius", losses)) is { } radius
            ? Round(radius * 2 * 0.75)
            : 6;

        int[]? stroke = paint["circle-stroke-color"] is { } line
            ? Colour(Hex(Constant(line, "circle-stroke-color", losses), "#000000"), 1)
            : null;

        double strokeWidth =
            Number(Constant(paint["circle-stroke-width"], "circle-stroke-width", losses))
                is { } sw ? Round(sw * 0.75) : 1;

        NoteZoomDependence(paint, losses);

        object Symbol(string hex, double alpha) => new
        {
            type = "esriSMS",
            style = "esriSMSCircle",
            color = Colour(hex, alpha),
            size,
            outline = stroke is null
                ? null
                : (object)new
                {
                    type = "esriSLS",
                    style = "esriSLSSolid",
                    color = stroke,
                    width = strokeWidth,
                },
        };

        return Classified(colour, opacity, layerName, Symbol, losses, "circle-color");
    }

    /// <summary>
    /// Turns one colour property into whichever of the three families it is.
    /// </summary>
    /// <remarks>
    /// <b>The renderer family is read out of the expression, not asked for.</b> A
    /// constant is a <c>simple</c> renderer, a <c>match</c> on a field is a
    /// <c>uniqueValue</c>, and a <c>step</c> is a <c>classBreaks</c> — which is the
    /// same correspondence the inbound direction uses, and the reason a
    /// <c>drawingInfo</c> can survive the round trip §7's third condition asks about.
    /// </remarks>
    private static object Classified(
        JsonNode? colour,
        double opacity,
        string layerName,
        Func<string, double, object> symbol,
        List<string> losses,
        string property)
    {
        if (colour is JsonArray expression && expression.Count > 0)
        {
            string head = Text(expression[0]) ?? string.Empty;

            if (string.Equals(head, "match", StringComparison.Ordinal))
            {
                return UniqueValueOut(expression, opacity, symbol, losses, property);
            }

            if (string.Equals(head, "step", StringComparison.Ordinal))
            {
                return ClassBreaksOut(expression, opacity, symbol, losses, property);
            }

            losses.Add(
                $"`{property}` is a `{head}` expression, which no Esri renderer family can "
                + "express. This face draws every feature in one colour; the expression survives "
                + "on the tile face.");

            return new
            {
                type = "simple",
                symbol = symbol("#888888", opacity),
                label = layerName,
                description = string.Empty,
            };
        }

        return new
        {
            type = "simple",
            symbol = symbol(Hex(colour, "#888888"), opacity),
            label = layerName,
            description = string.Empty,
        };
    }

    private static object UniqueValueOut(
        JsonArray match,
        double opacity,
        Func<string, double, object> symbol,
        List<string> losses,
        string property)
    {
        string field = FieldOf(match[1], property, losses);

        List<object> infos = new();

        // ["match", input, v1, c1, v2, c2, ..., fallback]
        for (int i = 2; i + 1 < match.Count; i += 2)
        {
            string value = Text(match[i]) ?? Number(match[i])?.ToString(CultureInfo.InvariantCulture)
                ?? string.Empty;

            infos.Add(new
            {
                value,
                label = value,
                description = string.Empty,
                symbol = symbol(Hex(match[i + 1], "#888888"), opacity),
            });
        }

        JsonNode? fallback = match.Count % 2 == 1 ? match[^1] : null;

        return new
        {
            type = "uniqueValue",
            field1 = field,
            field2 = (string?)null,
            field3 = (string?)null,
            fieldDelimiter = ",",
            defaultSymbol = fallback is null || IsTransparent(fallback)
                ? null
                : symbol(Hex(fallback, "#888888"), opacity),
            defaultLabel = "Other",
            uniqueValueInfos = infos,
        };
    }

    private static object ClassBreaksOut(
        JsonArray step,
        double opacity,
        Func<string, double, object> symbol,
        List<string> losses,
        string property)
    {
        string field = FieldOf(step[1], property, losses);

        // ["step", input, c0, b1, c1, b2, c2, ...]
        List<string> colours = new() { Hex(step[2], "#888888") };
        List<double> bounds = new();

        for (int i = 3; i + 1 < step.Count; i += 2)
        {
            bounds.Add(Number(step[i]) ?? 0);
            colours.Add(Hex(step[i + 1], "#888888"));
        }

        List<object> infos = new();
        double minimum = double.MinValue;

        for (int i = 0; i < colours.Count; i++)
        {
            // The last class has no upper stop in a `step` expression. Esri needs
            // one, so the last bound is reused — which is a real approximation and
            // is reported rather than left to be discovered from a legend.
            double maximum = i < bounds.Count
                ? bounds[i]
                : bounds.Count > 0 ? bounds[^1] : 0;

            infos.Add(new
            {
                classMinValue = minimum == double.MinValue ? (double?)null : minimum,
                classMaxValue = maximum,
                label = minimum == double.MinValue
                    ? $"< {maximum.ToString(CultureInfo.InvariantCulture)}"
                    : $"{minimum.ToString(CultureInfo.InvariantCulture)} – "
                      + maximum.ToString(CultureInfo.InvariantCulture),
                description = string.Empty,
                symbol = symbol(colours[i], opacity),
            });

            minimum = maximum;
        }

        if (colours.Count > bounds.Count)
        {
            losses.Add(
                "The last class of a `step` expression is unbounded above and an Esri class break "
                + "needs a maximum, so the last break value is repeated. A client's legend will "
                + "show the top class as narrower than it is.");
        }

        return new
        {
            type = "classBreaks",
            field,
            minValue = (double?)null,
            classBreakInfos = infos,
        };
    }

    private static string FieldOf(JsonNode? input, string property, List<string> losses)
    {
        if (input is JsonArray get && get.Count == 2
            && string.Equals(Text(get[0]), "get", StringComparison.Ordinal)
            && Text(get[1]) is { Length: > 0 } field)
        {
            return field;
        }

        losses.Add(
            $"`{property}` classifies on something other than a plain field lookup, and an Esri "
            + "renderer names a field. The field is reported as unknown.");

        return "unknown";
    }

    /// <summary>
    /// Reports a zoom-dependent paint property, which is the loss condition 2 names.
    /// </summary>
    /// <remarks>
    /// <b>This is the obvious case ADR-033 §7 asks to be tested, and it is the reason
    /// the report exists.</b> An Esri symbol has one width; a MapLibre paint property
    /// can be a function of zoom. Emitting the value at one zoom and saying nothing
    /// would be a server telling a client something untrue about the map — the line
    /// that is hairline at zoom 6 and heavy at zoom 14 arrives as one number, and no
    /// client can tell which.
    /// </remarks>
    private static void NoteZoomDependence(JsonObject paint, List<string> losses)
    {
        foreach (KeyValuePair<string, JsonNode?> property in paint)
        {
            if (property.Value is JsonArray expression && MentionsZoom(expression))
            {
                losses.Add(
                    $"`{property.Key}` varies with zoom. An Esri symbol carries one value, so this "
                    + "face reports the value at the lowest zoom stop and the variation survives "
                    + "on the tile face only.");
            }
        }

        static bool MentionsZoom(JsonNode node) => node switch
        {
            JsonArray a => a.Any(i => i is not null && MentionsZoom(i)),
            JsonValue v => v.TryGetValue(out string? s)
                && string.Equals(s, "zoom", StringComparison.Ordinal),
            _ => false,
        };
    }

    /// <summary>
    /// The value of a possibly zoom-dependent property, taken at its first stop.
    /// </summary>
    private static JsonNode? Constant(JsonNode? value, string property, List<string> losses)
    {
        if (value is not JsonArray expression || expression.Count == 0)
        {
            return value;
        }

        string head = Text(expression[0]) ?? string.Empty;

        // interpolate / step over zoom: the first output is the value at the lowest
        // stop. NoteZoomDependence has already said this is happening.
        if (head is "interpolate" or "interpolate-hcl" or "interpolate-lab")
        {
            return expression.Count > 4 ? expression[4] : null;
        }

        if (string.Equals(head, "step", StringComparison.Ordinal))
        {
            return expression.Count > 2 ? expression[2] : null;
        }

        losses.Add(
            $"`{property}` is a `{head}` expression and this face needs one value. It is reported "
            + "as the property's default.");

        return null;
    }

    // ------------------------------------------------------------------- plumbing

    private static string MapLibreTypeFor(GeometryKind geometry) => geometry switch
    {
        GeometryKind.Point or GeometryKind.MultiPoint => "circle",
        GeometryKind.LineString or GeometryKind.MultiLineString => "line",
        _ => "fill",
    };

    private static string ColourProperty(string type) => type switch
    {
        "fill" => "fill-color",
        "line" => "line-color",
        _ => "circle-color",
    };

    private static string StyleForDash(JsonArray dashes)
    {
        double[] pattern = dashes.Select(d => Number(d) ?? 0).ToArray();

        return pattern switch
        {
            [4, 3] => "esriSLSDash",
            [1, 3] => "esriSLSDot",
            [4, 3, 1, 3] => "esriSLSDashDot",
            [4, 3, 1, 3, 1, 3] => "esriSLSDashDotDot",
            _ => "esriSLSSolid",
        };
    }

    /// <summary>An Esri symbol colour as a CSS string MapLibre understands.</summary>
    private static string Rgba(JsonObject symbol, double layerOpacity)
    {
        if (symbol["color"] is not JsonArray colour || colour.Count < 3)
        {
            return "rgba(0,0,0,0)";
        }

        int red = (int)(Number(colour[0]) ?? 0);
        int green = (int)(Number(colour[1]) ?? 0);
        int blue = (int)(Number(colour[2]) ?? 0);
        double alpha = colour.Count > 3 ? (Number(colour[3]) ?? 255) / 255 : 1;

        alpha = Round(alpha * layerOpacity);

        return $"rgba({red},{green},{blue},{alpha.ToString(CultureInfo.InvariantCulture)})";
    }

    /// <summary>A MapLibre colour as Esri's <c>[r, g, b, a]</c>.</summary>
    private static int[] Colour(string css, double opacity)
    {
        (byte red, byte green, byte blue, double alpha) = Parse(css);
        return [red, green, blue, (int)Math.Round(alpha * opacity * 255)];
    }

    private static (byte Red, byte Green, byte Blue, double Alpha) Parse(string css)
    {
        string text = css.Trim();

        if (text.StartsWith('#'))
        {
            (byte r, byte g, byte b) = GeneratedSymbology.Bytes(text);
            return (r, g, b, 1);
        }

        if (text.StartsWith("rgb", StringComparison.OrdinalIgnoreCase)
            && text.IndexOf('(') is int open && open > 0)
        {
            string[] parts = text[(open + 1)..text.LastIndexOf(')')].Split(',');

            byte Component(int i) =>
                i < parts.Length
                && double.TryParse(parts[i].Trim(), NumberStyles.Float, CultureInfo.InvariantCulture,
                    out double v)
                    ? (byte)Math.Clamp((int)Math.Round(v), 0, 255)
                    : (byte)0;

            double alpha = parts.Length > 3
                && double.TryParse(parts[3].Trim(), NumberStyles.Float, CultureInfo.InvariantCulture,
                    out double a)
                    ? Math.Clamp(a, 0, 1)
                    : 1;

            return (Component(0), Component(1), Component(2), alpha);
        }

        // A named colour, or something this server does not parse. Grey rather than
        // a throw: a colour it cannot read is not a reason to refuse the document,
        // and the tile face renders it correctly regardless.
        return (0x88, 0x88, 0x88, 1);
    }

    private static string Hex(JsonNode? node, string fallback) =>
        Text(node) is { Length: > 0 } css ? css : fallback;

    private static bool IsTransparent(JsonNode? node) =>
        Text(node) is { } css && Parse(css).Alpha <= 0.0001;

    private static string? Text(JsonNode? node) =>
        node is JsonValue value && value.TryGetValue(out string? text) ? text : null;

    private static double? Number(JsonNode? node) =>
        node is JsonValue value && value.TryGetValue(out double number) ? number : null;

    /// <summary>
    /// Four decimal places, which is what makes the round trip exact.
    /// </summary>
    /// <remarks>
    /// A point is 4/3 of a pixel, so a whole number of points is a repeating decimal
    /// in pixels. Keeping four places means 2 pt → 2.6667 px → 2 pt, which is what
    /// §7's third condition needs; rounding to two would give 1.9998.
    /// </remarks>
    private static double Round(double value) => Math.Round(value, 4);

    private static string Serialise(JsonObject canonical) =>
        canonical.ToJsonString(new JsonSerializerOptions { WriteIndented = false });
}

/// <summary>A canonical document, and what was lost reaching it.</summary>
/// <param name="Canonical">The document to store.</param>
/// <param name="Losses">One sentence per thing that did not survive.</param>
/// <param name="Source">Which format came in, for the response to echo.</param>
public sealed record SymbologyWrite(
    string Canonical, IReadOnlyList<string> Losses, string Source);

/// <summary>An Esri <c>drawingInfo</c>, and what it could not carry.</summary>
/// <param name="DrawingInfo">Ready to serialise into a layer document.</param>
/// <param name="Losses">One sentence per thing this face cannot express.</param>
public sealed record DerivedDrawingInfo(
    JsonNode DrawingInfo, IReadOnlyList<string> Losses);

/// <summary>Thrown when a symbology document cannot be used.</summary>
public sealed class SymbologyException : Exception
{
    /// <summary>Creates the exception.</summary>
    public SymbologyException()
        : base("The symbology document could not be used.")
    {
    }

    /// <summary>Creates the exception.</summary>
    public SymbologyException(string message)
        : base(message)
    {
    }

    /// <summary>Creates the exception.</summary>
    public SymbologyException(string message, Exception innerException)
        : base(message, innerException)
    {
    }
}
