using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Xunit;

namespace Graticula.Conformance.Tests;

/// <summary>
/// A tile answered from this server's own store says how old it is.
/// </summary>
/// <remarks>
/// <para>
/// <b>[D-248](../../docs/architecture-debt.md).</b> A stored tile came back with
/// <c>Cache-Control: max-age</c>, a strong <c>ETag</c> and <c>X-Tile-Cache: HIT</c>, and
/// **no <c>Age</c>**. RFC 9111 §5.1 has a recipient treat a missing <c>Age</c> as zero, so
/// every cache in front of this one restarted the whole lifetime from its own receipt:
/// worst-case staleness was ours plus theirs, per layer of cache, and nothing in the
/// response said so.
/// </para>
/// <para>
/// <b>The number was never missing — it was discarded.</b>
/// <c>FileSystemTileCache.ReadAsync</c> reads the entry's stamp on every hit to decide
/// whether it is still fresh, and returned only the bytes. The stamp is this cache's own
/// clock, set on write and not moved by a read — <c>Touch</c> is in-memory LRU bookkeeping
/// — so it is the moment the tile was generated, which is what <c>Age</c> means.
/// </para>
/// <para>
/// <b>Found by walking [ADR-017](../../docs/adr/ADR-017-admin-api.md) §3.1</b> — *the map
/// is showing old data* — where it turned out to be partly a thing this server causes, and
/// the operator's own diagnostic agreed with the complaint while being useless about it.
/// </para>
/// <para>
/// <b>Asserted on a second fetch rather than a first.</b> A cold tile is generated by this
/// request and correctly carries no <c>Age</c>; the header is a claim about a stored
/// answer, so the test has to store one first.
/// </para>
/// </remarks>
[Collection("catalogue walk")]
public sealed class AStoredTileSaysHowOldItIsTests : ArcGisClient
{
    private const string ServiceVariable = "GRATICULA_TEST_TILE_SERVICE";

    /// <summary>A hit carries Age; a miss does not.</summary>
    [Fact]
    public async Task A_hit_carries_an_age_and_a_miss_does_not()
    {
        string root = await RequireServerAsync();
        string? service = Environment.GetEnvironmentVariable(ServiceVariable);

        Assert.False(
            string.IsNullOrWhiteSpace(service),
            $"{ServiceVariable} is not set, so this test FAILS rather than skips.");

        Uri tile = new(
            $"{root}/rest/services/{service!.Trim('/')}/VectorTileServer/tile/12/1550/2421.pbf");

        // Two fetches: whatever the first does, the second is answered from the store.
        (string? firstState, string? firstAge) = await FetchAsync(tile);
        (string? state, string? age) = await FetchAsync(tile);

        Assert.Equal("HIT", state);

        Assert.True(
            age is { Length: > 0 },
            "A tile answered from this server's own store carried no `Age`. RFC 9111 §5.1 "
            + "has a proxy treat that as zero and restart the whole `max-age` from its own "
            + "receipt, so the worst case is our lifetime plus theirs, per layer of cache. "
            + "The number is in the cache already — `FileSystemTileCache` reads the entry's "
            + "stamp on every hit to decide freshness. D-248.");

        Assert.True(
            long.TryParse(age, NumberStyles.None, CultureInfo.InvariantCulture, out long seconds)
                && seconds >= 0,
            $"`Age: {age}` is not a non-negative number of seconds.");

        // <b>And a freshly built tile does not claim one</b>, which is the half that keeps
        // the header a signal rather than decoration: it is a statement about a stored
        // answer, and a response this request generated has no store behind it.
        if (firstState == "MISS")
        {
            Assert.True(
                firstAge is null,
                $"A MISS carried `Age: {firstAge}`. That response was generated by this "
                + "request, so there is no age to report.");
        }
    }

    private async Task<(string? State, string? Age)> FetchAsync(Uri tile)
    {
        using HttpResponseMessage response = await Http.GetAsync(tile);

        response.EnsureSuccessStatusCode();

        return (One(response, "X-Tile-Cache"), One(response, "Age"));
    }

    /// <summary>
    /// One header value, from wherever .NET filed it.
    /// </summary>
    /// <remarks>
    /// <b>Both collections, because .NET sorts headers and HTTP does not.</b> `Age` is a
    /// response header it knows and `X-Tile-Cache` is not, so they land in different
    /// places — and asking only one is how a test reports a missing header that is being
    /// sent, which cost a measurement earlier the same day.
    /// </remarks>
    /// <param name="response">The response.</param>
    /// <param name="name">The header.</param>
    /// <returns>Its first value, or null.</returns>
    private static string? One(HttpResponseMessage response, string name) =>
        response.Headers.TryGetValues(name, out IEnumerable<string>? said)
        || response.Content.Headers.TryGetValues(name, out said)
            ? said.FirstOrDefault()
            : null;
}
