using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

namespace Graticula.Api.ArcGis;

/// <summary>
/// A cartographic style somebody wrote, checked before it is stored.
/// </summary>
/// <remarks>
/// <para>
/// <b>The generated style was always a placeholder.</b> Every polygon came out
/// the same blue in publication order, because choosing a colour depends on what
/// a layer means, what it sits on, and who is looking — none of which a server
/// knows. This is the type that lets somebody who does know say so.
/// </para>
/// <para>
/// <b>Validated on the way in, not on the way out.</b> A style is written once
/// and served thousands of times; checking at write is where the person who can
/// fix it is still holding it. It also means the serving path stays a read.
/// </para>
/// <para>
/// <b>The checks are the ones that fail silently otherwise.</b> A style with a
/// mistyped <c>source-layer</c> renders a blank map and reports nothing — the
/// client is behaving correctly, the tiles are correct, and there is no error
/// anywhere. That is the single most common authoring mistake and the one worth
/// a round trip. The rest are security: a style is a document this server hands
/// to a browser, and a browser will fetch whatever URLs are in it.
/// </para>
/// </remarks>
public static class StyleDocument
{
    /// <summary>The largest style this server will store.</summary>
    /// <remarks>
    /// A megabyte. Real styles are tens of kilobytes, so this is a bound on
    /// abuse rather than a limit anybody meets — a style that reaches it was
    /// generated by accident, and the column has a matching constraint so the
    /// bound cannot be bypassed by a second writer.
    /// </remarks>
    public const int MaximumBytes = 1024 * 1024;

    /// <summary>The style spec version this server understands.</summary>
    public const int Version = 8;

    /// <summary>
    /// Checks a style against the service it is for.
    /// </summary>
    /// <param name="json">The document as it was sent.</param>
    /// <param name="sourceLayers">The layer names the service actually has.</param>
    /// <param name="icons">
    /// The icon names the service's sprite sheet defines — the 1x sheet's, which is the one every
    /// client can fall back to — or null when the service has no sheet at all (ADR-092). Null and
    /// empty are different answers: null refuses any <c>icon-image</c> and says to upload a sheet,
    /// empty refuses every literal name as missing from the one that is there.
    /// </param>
    /// <param name="error">Why it was refused, naming what to change.</param>
    /// <returns>True when it is safe to store.</returns>
    public static bool TryValidate(
        string? json,
        IReadOnlyCollection<string> sourceLayers,
        IReadOnlyCollection<string>? icons,
        out string? error) =>
        TryValidate(json, sourceLayers, icons, allowed: null, out error);

    /// <summary>
    /// Checks a style against the service it is for and the external origins this server allows — ADR-094.
    /// </summary>
    /// <param name="json">The document as it was sent.</param>
    /// <param name="sourceLayers">The layer names the service actually has.</param>
    /// <param name="icons">The 1x sprite sheet's icon names, or null when there is no sheet (ADR-092).</param>
    /// <param name="allowed">
    /// The origins an administrator allows a style to fetch from, or null (or empty) for none — which is
    /// ADR-028 §5's rule, unchanged: nothing leaves this server.
    /// </param>
    /// <param name="error">Why it was refused, naming what to change.</param>
    /// <returns>True when it is safe to store, or to serve.</returns>
    /// <remarks>
    /// <b>The same call on the way in and on the way out.</b> An origin taken off the list does not
    /// reach into the store and edit the styles that named it; they stop passing this check where they
    /// are served, and the generated style is served instead, the way a style that outlived its layers
    /// is (ADR-028 condition 3).
    /// </remarks>
    public static bool TryValidate(
        string? json,
        IReadOnlyCollection<string> sourceLayers,
        IReadOnlyCollection<string>? icons,
        IReadOnlyCollection<StyleOrigin>? allowed,
        out string? error)
    {
        ArgumentNullException.ThrowIfNull(sourceLayers);

        error = null;

        if (string.IsNullOrWhiteSpace(json))
        {
            error = "A style document is required. To go back to the generated default, "
                  + "DELETE this resource rather than sending an empty one.";
            return false;
        }

        if (System.Text.Encoding.UTF8.GetByteCount(json) > MaximumBytes)
        {
            error = $"A style may be at most {MaximumBytes / 1024} KB. Real styles are tens of "
                  + "kilobytes; one this size is usually a generated file sent by mistake.";
            return false;
        }

        JsonDocument document;

        try
        {
            // Depth is bounded by the reader rather than by us. A style is
            // nested a handful of levels; anything approaching the default 64
            // is not a style, and a parser is a decompressor too.
            document = JsonDocument.Parse(json, new JsonDocumentOptions { MaxDepth = 32 });
        }
        catch (JsonException e)
        {
            error = $"The style is not valid JSON: {e.Message}";
            return false;
        }

        using (document)
        {
            return Check(document.RootElement, sourceLayers, icons, allowed, out error);
        }
    }

    private static bool Check(
        JsonElement root,
        IReadOnlyCollection<string> sourceLayers,
        IReadOnlyCollection<string>? icons,
        IReadOnlyCollection<StyleOrigin>? allowed,
        out string? error)
    {
        error = null;

        if (root.ValueKind != JsonValueKind.Object)
        {
            error = "A style is a JSON object.";
            return false;
        }

        if (!root.TryGetProperty("version", out JsonElement version)
            || version.ValueKind != JsonValueKind.Number
            || !version.TryGetInt32(out int number)
            || number != Version)
        {
            error = $"A style must declare \"version\": {Version}. That is the only style "
                  + "specification version this server serves, and a client reads the version "
                  + "before anything else.";
            return false;
        }

        if (!root.TryGetProperty("layers", out JsonElement layers)
            || layers.ValueKind != JsonValueKind.Array)
        {
            error = "A style must have a \"layers\" array. An empty one is allowed and draws "
                  + "nothing, which is different from having none.";
            return false;
        }

        if (!Urls(root, allowed, out error))
        {
            return false;
        }

        return Layers(layers, sourceLayers, icons, out error);
    }

    /// <summary>
    /// Nothing in the document may point off this server, except at an origin an administrator allowed.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Two reasons, and the second is the one people miss.</b> Q-15 requires
    /// air-gapped operation, so a style fetching tiles or fonts from the
    /// internet is broken in the deployments this product is for.
    /// </para>
    /// <para>
    /// <b>And a style is a document we hand to a browser.</b> Whatever URLs it
    /// contains, that browser fetches — with the user's network position. A
    /// style stored by one publisher and viewed by everybody else in the
    /// organisation is a way to make their browsers reach an address of the
    /// publisher's choosing, and to learn who looked at the map and when.
    /// Relative URLs only, checked rather than rewritten.
    /// </para>
    /// <para>
    /// <b>Amended 2026-09-29 by ADR-094: unless an administrator allowed the origin.</b> A basemap
    /// vendor's tiles are a legitimate thing for a style to draw, and the objection above is to a
    /// <em>publisher</em> choosing where every viewer's browser goes. An administrator choosing a
    /// short list of https origins is a different person making a different decision, audited, and
    /// the same list is what the console's security policy allows. With the list empty — the
    /// default — the rule is exactly what it was.
    /// </para>
    /// <para>
    /// <b>Every place a style names a URL, not only the four the rule's first draft read.</b> A
    /// <c>sprite</c> may be an array of <c>{id, url}</c> since MapLibre's multiple sprites; a video
    /// source has <c>urls</c>. Until 2026-09-29 neither was read at all, so a style could name any
    /// host through either and pass — the rule was one spelling short of itself.
    /// </para>
    /// </remarks>
    private static bool Urls(JsonElement root, IReadOnlyCollection<StyleOrigin>? allowed, out string? error)
    {
        error = null;

        if (root.TryGetProperty("glyphs", out JsonElement glyphs)
            && glyphs.ValueKind == JsonValueKind.String
            && !Allowed(glyphs.GetString(), allowed))
        {
            error = Refusal("\"glyphs\"", glyphs.GetString(), allowed);
            return false;
        }

        if (root.TryGetProperty("sprite", out JsonElement sprite))
        {
            foreach (string? candidate in Strings(sprite, member: "url"))
            {
                if (!Allowed(candidate, allowed))
                {
                    error = Refusal("\"sprite\"", candidate, allowed);
                    return false;
                }
            }
        }

        if (!root.TryGetProperty("sources", out JsonElement sources)
            || sources.ValueKind != JsonValueKind.Object)
        {
            return true;
        }

        foreach (JsonProperty source in sources.EnumerateObject())
        {
            if (source.Value.ValueKind != JsonValueKind.Object)
            {
                continue;
            }

            foreach (string key in (string[])["url", "tiles", "data", "urls"])
            {
                if (!source.Value.TryGetProperty(key, out JsonElement value))
                {
                    continue;
                }

                // An inline GeoJSON `data` is an object and names no URL. It was read as a string until
                // 2026-09-29, which threw — a 500 for a valid style — rather than accepting it.
                foreach (string? candidate in Strings(value, member: null))
                {
                    if (!Allowed(candidate, allowed))
                    {
                        error = Refusal($"Source '{source.Name}'", candidate, allowed);
                        return false;
                    }
                }
            }
        }

        return true;
    }

    /// <summary>The strings a URL-bearing value holds: itself, its elements, or each element's <paramref name="member"/>.</summary>
    private static IEnumerable<string?> Strings(JsonElement value, string? member)
    {
        if (value.ValueKind == JsonValueKind.String)
        {
            yield return value.GetString();
            yield break;
        }

        if (value.ValueKind != JsonValueKind.Array)
        {
            yield break;
        }

        foreach (JsonElement item in value.EnumerateArray())
        {
            if (item.ValueKind == JsonValueKind.String)
            {
                yield return item.GetString();
            }
            else if (member is not null
                     && item.ValueKind == JsonValueKind.Object
                     && item.TryGetProperty(member, out JsonElement inner)
                     && inner.ValueKind == JsonValueKind.String)
            {
                yield return inner.GetString();
            }
        }
    }

    /// <summary>Whether a URL stays on this server or goes to an allowed origin.</summary>
    private static bool Allowed(string? url, IReadOnlyCollection<StyleOrigin>? allowed) =>
        IsLocal(url) || StyleOrigins.Admits(url, allowed);

    /// <summary>
    /// Whether a stored style names any absolute URL — so a caller knows whether the allowlist has to be read at all.
    /// </summary>
    /// <param name="json">A stored style.</param>
    /// <returns>True when the document could name another host.</returns>
    /// <remarks>
    /// <b>A cheap over-approximation, on purpose.</b> Serving a style reads the store for the list only
    /// when the answer could depend on it; a document with no <c>//</c> in it cannot name an https origin,
    /// and one that has it for another reason pays one extra read.
    /// </remarks>
    public static bool MayNameAnotherHost(string? json) =>
        json is not null && json.Contains("//", StringComparison.Ordinal);

    /// <summary>
    /// The refusal for a URL that leaves this server, naming its origin and where an administrator allows one.
    /// </summary>
    private static string Refusal(string what, string? url, IReadOnlyCollection<StyleOrigin>? allowed)
    {
        string? origin = StyleOrigins.OriginOf(url);

        if (origin is null)
        {
            // Not an https origin at all — `http:`, `//host`, `javascript:`, a root-relative path, or a URL
            // with something in its host that a browser could read two ways.
            StyleOrigins.TryReadUrl(url, out _, out _, out string? why);

            return $"{what} points at '{url}'. A style may name relative URLs on this server, and https URLs "
                 + "on origins an administrator has allowed"
                 + (url is { Length: > 0 } && url.StartsWith("https://", StringComparison.OrdinalIgnoreCase)
                     ? $"; this one cannot be allowed, because {why}. "
                     : ". ")
                 + "A style is fetched by every viewer's browser, so an absolute URL sends every viewer of this "
                 + "map to another host — and it cannot work in an air-gapped deployment.";
        }

        return $"{what} points at '{url}', on {origin}, which is not an origin this server allows styles to "
             + "fetch from"
             + (allowed is { Count: > 0 }
                 ? $" (it allows {string.Join(", ", allowed.Select(a => a.Text))})"
                 : " (it allows none)")
             + ". An administrator can add it under Server › Settings › Style sources, or with "
             + "PUT /admin/settings/style-origins. A style is fetched by every viewer's browser, so which "
             + "hosts it may send them to is the server's decision, not the style author's.";
    }

    /// <summary>
    /// Whether a URL stays on this server.
    /// </summary>
    /// <remarks>
    /// <b>Refuses a scheme, a protocol-relative URL and a root-relative one.</b>
    /// The first two leave the host. The third — <c>/anything</c> — stays on the
    /// host but leaves the service, and a style is served from a path whose
    /// meaning is relative to it; allowing an absolute path would let a style
    /// for one service address another's resources, which is a sharing boundary
    /// expressed as a URL.
    /// </remarks>
    private static bool IsLocal(string? url) =>
        !string.IsNullOrWhiteSpace(url)
        && !url.StartsWith("//", StringComparison.Ordinal)
        && !url.StartsWith('/')
        && !url.Contains("://", StringComparison.Ordinal)
        && !url.Contains(':', StringComparison.Ordinal);


    /// <summary>
    /// Whether a layer draws an icon the service's sprite sheet can supply — ADR-092.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Until 2026-09-29 every <c>icon-image</c> was refused</b>, because the sheet was empty and
    /// nobody could fill it (ADR-027 condition 5, ADR-028 condition 4). That refusal is deleted, as
    /// both conditions asked, rather than relaxed: what replaces it is the source-layer check's
    /// shape applied to icons.
    /// </para>
    /// <para>
    /// <b>No sheet, no icons.</b> An <c>icon-image</c> on a service with no sprite sheet renders
    /// nothing and logs nothing, so it is refused with the one step that fixes it.
    /// </para>
    /// <para>
    /// <b>A literal name must be in the sheet</b> — a string, or <c>["literal", name]</c> — for the
    /// reason a mistyped source layer must be in the service: a missing icon is a blank with no
    /// error anywhere. <b>An expression is accepted and not resolved</b>, because which names it
    /// produces depends on the features; so is a legacy <c>{token}</c> string, which is an
    /// expression spelled as text.
    /// </para>
    /// </remarks>
    private static bool Icon(
        JsonElement layer, string id, IReadOnlyCollection<string>? icons, out string? error)
    {
        error = null;

        if (!layer.TryGetProperty("layout", out JsonElement layout)
            || layout.ValueKind != JsonValueKind.Object
            || !layout.TryGetProperty("icon-image", out JsonElement icon)
            || icon.ValueKind is JsonValueKind.Null)
        {
            return true;
        }

        if (icons is null)
        {
            error = $"Layer '{id}' sets \"icon-image\", and this service has no sprite sheet to draw it "
                  + "from. Upload one first — PUT /admin/services/{name}/sprite with the sheet's sprite.json "
                  + "and sprite.png — and then store this style. Without it the layer would render nothing "
                  + "and report nothing, so it is refused here instead.";
            return false;
        }

        if (LiteralIcon(icon) is { } named && !icons.Contains(named, StringComparer.Ordinal))
        {
            error = $"Layer '{id}' draws icon '{named}', which this service's sprite sheet does not have. "
                  + (icons.Count == 0
                      ? "The sheet names no icons at all. "
                      : $"It has {icons.Count} icon{(icons.Count == 1 ? "" : "s")}, among them: "
                        + string.Join(", ", icons.Take(20)) + (icons.Count > 20 ? ", …" : "") + ". ")
                  + "A style naming an icon that is not there draws nothing where it should be and reports "
                  + "nothing, which is why this is refused rather than stored.";
            return false;
        }

        return true;
    }

    /// <summary>
    /// The icon name an <c>icon-image</c> value names outright, or null when it is an expression.
    /// </summary>
    /// <param name="icon">The layout value.</param>
    /// <returns>The name, or null.</returns>
    private static string? LiteralIcon(JsonElement icon)
    {
        if (icon.ValueKind == JsonValueKind.String)
        {
            string text = icon.GetString()!;

            // `{name}` substitutes a feature's attribute: the legacy token syntax, which is an
            // expression written as a string.
            return text.Contains('{', StringComparison.Ordinal) ? null : text;
        }

        if (icon.ValueKind == JsonValueKind.Array
            && icon.GetArrayLength() == 2
            && icon[0].ValueKind == JsonValueKind.String
            && string.Equals(icon[0].GetString(), "literal", StringComparison.Ordinal)
            && icon[1].ValueKind == JsonValueKind.String)
        {
            return icon[1].GetString();
        }

        return null;
    }

    /// <summary>
    /// Every icon name a style's layers draw outright, for refusing a sprite sheet that would take
    /// one away — ADR-092.
    /// </summary>
    /// <param name="json">A stored style.</param>
    /// <returns>
    /// The literal names, each once, in the order the layers use them; empty when the document
    /// cannot be read.
    /// </returns>
    /// <remarks>
    /// <b>The other direction of the same check.</b> <see cref="TryValidate(string?, IReadOnlyCollection{string}, IReadOnlyCollection{string}?, IReadOnlyCollection{StyleOrigin}?, out string?)"/> refuses a style naming
    /// an icon the sheet lacks; this lets the sheet's own routes refuse a replacement or a removal
    /// that would leave a stored style in that state. Expressions are skipped here for the reason
    /// they are accepted there.
    /// </remarks>
    public static IReadOnlyList<string> LiteralIcons(string? json)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return [];
        }

        try
        {
            using JsonDocument document = JsonDocument.Parse(json, new JsonDocumentOptions { MaxDepth = 32 });

            if (document.RootElement.ValueKind != JsonValueKind.Object
                || !document.RootElement.TryGetProperty("layers", out JsonElement layers)
                || layers.ValueKind != JsonValueKind.Array)
            {
                return [];
            }

            List<string> names = [];

            foreach (JsonElement layer in layers.EnumerateArray())
            {
                if (layer.ValueKind == JsonValueKind.Object
                    && layer.TryGetProperty("layout", out JsonElement layout)
                    && layout.ValueKind == JsonValueKind.Object
                    && layout.TryGetProperty("icon-image", out JsonElement icon)
                    && LiteralIcon(icon) is { } named
                    && !names.Contains(named, StringComparer.Ordinal))
                {
                    names.Add(named);
                }
            }

            return names;
        }
        catch (JsonException)
        {
            return [];
        }
    }

    /// <summary>
    /// Every layer must name a source layer that exists.
    /// </summary>
    /// <remarks>
    /// <b>The check that pays for this whole type.</b> A mistyped
    /// <c>source-layer</c> produces a map with nothing on it, no error in the
    /// client, no error in the server, and correct tiles — so the author looks
    /// for the bug everywhere except the one line that has it.
    /// </remarks>
    private static bool Layers(
        JsonElement layers,
        IReadOnlyCollection<string> sourceLayers,
        IReadOnlyCollection<string>? icons,
        out string? error)
    {
        error = null;

        int index = -1;

        foreach (JsonElement layer in layers.EnumerateArray())
        {
            index++;

            if (layer.ValueKind != JsonValueKind.Object)
            {
                error = $"Layer {index} is not an object.";
                return false;
            }

            if (!layer.TryGetProperty("id", out JsonElement id)
                || id.ValueKind != JsonValueKind.String
                || string.IsNullOrWhiteSpace(id.GetString()))
            {
                error = $"Layer {index} needs an \"id\". A client keys everything off it, "
                      + "including which layer an error is about.";
                return false;
            }

            if (!layer.TryGetProperty("source-layer", out JsonElement sourceLayer)
                || sourceLayer.ValueKind != JsonValueKind.String)
            {
                // Background layers legitimately have no source.
                if (layer.TryGetProperty("type", out JsonElement type)
                    && type.ValueKind == JsonValueKind.String
                    && string.Equals(type.GetString(), "background", StringComparison.Ordinal))
                {
                    continue;
                }

                error = $"Layer '{id.GetString()}' has no \"source-layer\". Only a background "
                      + "layer may leave it out.";
                return false;
            }

            if (!Icon(layer, id.GetString()!, icons, out error))
            {
                return false;
            }

            string named = sourceLayer.GetString()!;

            if (!sourceLayers.Contains(named, StringComparer.Ordinal))
            {
                error = $"Layer '{id.GetString()}' draws source-layer '{named}', which this "
                      + $"service does not have. It has: {string.Join(", ", sourceLayers)}. A "
                      + "style naming a layer that is not there renders an empty map and reports "
                      + "nothing, which is why this is refused rather than stored.";

                return false;
            }
        }

        return true;
    }
}
