<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Graticula.Security.Argon2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graticula.Platform\Graticula.Platform.csproj" />
  </ItemGroup>

</Project>
