using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Graticula.Catalog;
using Graticula.Features;
using Graticula.Geometries;
using Graticula.Providers.DuckDb;
using Graticula.Providers.PostGis;
using Graticula.Testing;
using SortKey = Graticula.Features.SortKey;
using Npgsql;
using Xunit;

namespace Graticula.Platform.Postgres.Tests;

/// <summary>
/// The same rows served from a PostGIS table and from a GeoParquet file, asked the same questions
/// — ADR-066 condition 1.
/// </summary>
/// <remarks>
/// <para>
/// <b>PostGIS is the oracle for the whole provider, not only for its predicate.</b>
/// <c>GeometryPredicates</c> is checked against <c>ST_Intersects</c> on real polygons elsewhere;
/// what that cannot show is that the two passes around it — the box test in DuckDB, the identities
/// carried back, the where clause emitted a second time, the projection through the datastore —
/// put together an answer PostGIS would give. So the rows are generated by PostGIS, written to a
/// file in the shape GDAL writes, and every query below is put to both providers.
/// </para>
/// <para>
/// <b>Shapes PostGIS made, not shapes drawn for the test</b>: buffered points with sixteen-sided
/// rings, a fifth of them with a hole, scattered at web-Mercator magnitudes over Anatolia, where a
/// double's step is a few nanometres and a single-precision box is a fifth of a metre wide.
/// </para>
/// <para>
/// <b>Two places the answers are allowed to differ, each for a measured reason</b>: an extent,
/// which PostGIS computes from the single-precision boxes it caches on each geometry and so rounds
/// outwards, and nothing else. Where the ids differ on an intersects, the test fails and prints the
/// pair, because that is a finding about <c>GeometryPredicates</c> rather than a tolerance to
/// widen (Q-20).
/// </para>
/// </remarks>
[Trait("Category", "Integration")]
public sealed class GeoParquetAgainstPostgisTests : PostgresFixture
{
    private const int Srid = 3857;
    private const int Rows = 1500;

    private static readonly string[] Columns = ["objectid", "name", "kind", "area", "day", "score"];

    private static readonly Dictionary<string, FieldType> Types = new() { ["day"] = FieldType.Date };

    private async Task<(IFeatureSource PostGis, GeoParquetFeatureSource Parquet, GeoParquetFolder Folder, string Path)> SourcesAsync()
    {
        await using (NpgsqlCommand create = DataSource.CreateCommand($"""
            create table shapes (
              objectid bigint primary key, name text, kind text, area double precision, day date,
              score integer, geom geometry(MultiPolygon, {Srid}));

            insert into shapes
            select i,
                   'n' || i,
                   (array['field', 'forest', 'water'])[1 + i % 3],
                   round((st_area(g) / 1000.0)::numeric, 3)::double precision,
                   date '2026-01-01' + i,
                   i % 7,
                   g
            from (
              select i,
                     st_multi(case when i % 5 = 0
                       then st_difference(
                              st_buffer(c, r, 'quad_segs=4'),
                              st_buffer(c, r / 3, 'quad_segs=4'))
                       else st_buffer(c, r, 'quad_segs=4') end) as g
              from (
                select i,
                       st_setsrid(st_makepoint(
                         2900000 + ((i * 7919) % 10007) * 150.0 + (i % 13) * 0.37,
                         4300000 + ((i * 104729) % 10009) * 70.0 + (i % 11) * 0.29), {Srid}) as c,
                       400 + ((i * 31) % 97) * 60.0 as r
                from generate_series(1, {Rows}) as i
              ) points
            ) shaped;

            create index on shapes using gist (geom);
            analyze shapes;
            """))
        {
            await create.ExecuteNonQueryAsync(CancellationToken.None);
        }

        List<(object?[] Values, Geometry? Shape)> rows = [];

        await using (NpgsqlCommand read = DataSource.CreateCommand(
            "select objectid, name, kind, area, day, score, st_asbinary(geom) from shapes order by objectid"))
        await using (NpgsqlDataReader reader = await read.ExecuteReaderAsync(CancellationToken.None))
        {
            while (await reader.ReadAsync(CancellationToken.None))
            {
                rows.Add((
                    [reader.GetInt64(0), reader.GetString(1), reader.GetString(2), reader.GetDouble(3),
                        DateOnly.FromDateTime(reader.GetDateTime(4)), reader.GetInt32(5)],
                    WkbReader.Read((byte[])reader[6])));
            }
        }

        string folder = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "graticula-oracle-" + Guid.NewGuid().ToString("n")[..12]);
        Directory.CreateDirectory(folder);

        GeoParquetFixture.Write(
            System.IO.Path.Combine(folder, "shapes.parquet"),
            [new("objectid", "BIGINT"), new("name", "VARCHAR"), new("kind", "VARCHAR"),
                new("area", "DOUBLE"), new("day", "DATE"), new("score", "INTEGER")],
            rows,
            srid: Srid);

        GeoParquetFolder parquet = new(folder, new GeoParquetOptions { MemoryLimit = "256MB", Threads = 2 });

        return (
            new PostGisFeatureSource(
                DataSource, new LayerDefinition("shapes", SchemaName, "shapes", "geom", Srid, "objectid", "objectid", false)),
            new GeoParquetFeatureSource(
                parquet, new LayerDefinition("shapes", "main", "shapes", "geom", Srid, "objectid", "objectid", false),
                new PostGisProjector(DataSource)),
            parquet,
            folder);
    }

    private static ParsedWhere Where(string clause)
    {
        Assert.True(
            WhereClause.TryParse(clause, Columns, LayerDefinition.Quote, out ParsedWhere parsed, out string? error, Types),
            error);

        return parsed;
    }

    private static async Task<List<Feature>> ReadAsync(IFeatureSource source, FeatureQuery query)
    {
        List<Feature> features = [];

        await foreach (Feature feature in source.ReadAsync(query, CancellationToken.None))
        {
            features.Add(feature);
        }

        return features;
    }

    private async Task<List<Geometry>> FiltersAsync()
    {
        // Real shapes from the table as filters, and three kinds of thing a client sends that a
        // table does not hold: a line across the area, a rectangle, and a point on a vertex.
        List<Geometry> filters = [];

        await using (NpgsqlCommand read = DataSource.CreateCommand(
            "select st_asbinary(st_geometryn(geom, 1)) from shapes where objectid % 97 = 1 order by objectid"))
        await using (NpgsqlDataReader reader = await read.ExecuteReaderAsync(CancellationToken.None))
        {
            while (await reader.ReadAsync(CancellationToken.None))
            {
                Polygon polygon = (Polygon)WkbReader.Read((byte[])reader[0]);
                filters.Add(polygon);

                // A vertex of the shell: on the boundary of this shape and of nothing else, unless
                // a neighbour's ring passes through the same coordinate — which is the question.
                filters.Add(new Point(polygon.Shell.Coordinates.X(3), polygon.Shell.Coordinates.Y(3)));
            }
        }

        for (int i = 0; i < 12; i++)
        {
            double x = 2_900_000 + (i * 120_000), y = 4_300_000 + (i * 55_000);

            filters.Add(new LineString(XySequence.Wrap([x, y, x + 400_000, y + 90_000, x + 410_000, y + 300_000])));
            filters.Add(new Polygon(new LinearRing(XySequence.Wrap(
                [x, y, x + 30_000, y, x + 30_000, y + 20_000, x, y + 20_000, x, y]))));
        }

        return filters;
    }

    [Fact]
    public async Task Intersects_returns_the_same_features_from_both_providers()
    {
        (IFeatureSource postgis, GeoParquetFeatureSource parquet, GeoParquetFolder folder, string path) = await SourcesAsync();

        try
        {
            List<Geometry> filters = await FiltersAsync();
            int compared = 0, matched = 0;
            List<string> disagreements = [];

            foreach (Geometry filter in filters)
            {
                FeatureQuery query = new(FeatureQuery.MaximumLimit, includeGeometry: false, spatial: new SpatialFilter(filter));

                long[] expected = [.. (await ReadAsync(postgis, query)).Select(f => long.Parse(f.Id, CultureInfo.InvariantCulture))];
                long[] actual = [.. (await ReadAsync(parquet, query)).Select(f => long.Parse(f.Id, CultureInfo.InvariantCulture))];

                compared++;
                matched += expected.Length;

                if (!expected.SequenceEqual(actual))
                {
                    disagreements.Add(
                        $"{filter.Kind} at {filter.Envelope}: PostGIS [{string.Join(",", expected.Except(actual))}] only, "
                        + $"GeoParquet [{string.Join(",", actual.Except(expected))}] only");
                }
                else if (await parquet.CountAsync(query, CancellationToken.None) is var counted && counted != expected.Length)
                {
                    disagreements.Add($"{filter.Kind} at {filter.Envelope}: {expected.Length} read and {counted} counted");
                }
            }

            Assert.True(compared >= 40, $"Only {compared} filters were compared.");
            Assert.True(matched >= 100, $"The filters matched only {matched} features between them, which proves little.");
            Assert.True(disagreements.Count == 0, string.Join(Environment.NewLine, disagreements));
        }
        finally
        {
            folder.Dispose();
            Directory.Delete(path, recursive: true);
        }
    }

    [Fact]
    public async Task Boxes_where_clauses_paging_and_projection_agree()
    {
        (IFeatureSource postgis, GeoParquetFeatureSource parquet, GeoParquetFolder folder, string path) = await SourcesAsync();

        try
        {
            List<FeatureQuery> queries = [];

            for (int i = 0; i < 10; i++)
            {
                double x = 2_950_000 + (i * 130_000), y = 4_350_000 + (i * 60_000);
                Envelope box = new(x, y, x + 150_000, y + 90_000);

                queries.Add(new FeatureQuery(FeatureQuery.MaximumLimit, boundingBox: box, fields: Columns));
                queries.Add(new FeatureQuery(40, boundingBox: box, fields: ["kind", "score"], offset: 5,
                    orderBy: [new SortKey("kind", false), new SortKey("score", true)]));
                queries.Add(new FeatureQuery(FeatureQuery.MaximumLimit, boundingBox: box,
                    where: Where("kind in ('field', 'water') and score >= 3 and name like 'n1%'")));
            }

            queries.Add(new FeatureQuery(FeatureQuery.MaximumLimit, where: Where("day between '2026-02-01' and '2026-03-01' or area > 9000")));
            queries.Add(new FeatureQuery(FeatureQuery.MaximumLimit, where: Where("not (kind = 'forest') and objectid < 300")));
            queries.Add(new FeatureQuery(100, fields: ["kind"], includeGeometry: false, distinct: true));

            // A box stated in longitude and latitude, which both providers bring into the layer's
            // reference through the same PROJ, and output in longitude and latitude.
            queries.Add(new FeatureQuery(FeatureQuery.MaximumLimit, boundingBox: new Envelope(27.5, 37.5, 29.5, 39.0),
                fields: ["name"], filterSrid: 4326, outSrid: 4326));

            int largest = 0;

            foreach (FeatureQuery query in queries)
            {
                List<Feature> expected = await ReadAsync(postgis, query);
                List<Feature> actual = await ReadAsync(parquet, query);
                largest = Math.Max(largest, expected.Count);

                // A distinct row's identity is whichever row the engine met first in its group, and
                // neither engine promises which; the combinations are the answer.
                if (!query.Distinct)
                {
                    Assert.Equal(expected.Select(f => f.Id), actual.Select(f => f.Id));
                }

                for (int i = 0; i < expected.Count; i++)
                {
                    foreach (string field in expected[i].Schema.Names)
                    {
                        Assert.Equal(Comparable(expected[i][field]), Comparable(actual[i][field]));
                    }

                    if (expected[i].Geometry is { } shape)
                    {
                        Envelope a = shape.Envelope, b = actual[i].Geometry!.Envelope;

                        // The same PROJ over the same doubles, so the same doubles back.
                        Assert.True(
                            Near(a.MinX, b.MinX, 1e-9) && Near(a.MinY, b.MinY, 1e-9) && Near(a.MaxX, b.MaxX, 1e-9) && Near(a.MaxY, b.MaxY, 1e-9),
                            $"Feature {expected[i].Id}: PostGIS {a}, GeoParquet {b}.");
                    }
                }

                Assert.Equal(
                    await postgis.CountAsync(query, CancellationToken.None),
                    await parquet.CountAsync(query, CancellationToken.None));
            }

            Assert.True(largest > 50, $"The largest answer was {largest} features, which proves little.");
        }
        finally
        {
            folder.Dispose();
            Directory.Delete(path, recursive: true);
        }
    }

    [Fact]
    public async Task Ids_extents_and_statistics_agree()
    {
        (IFeatureSource postgisSource, GeoParquetFeatureSource parquet, GeoParquetFolder folder, string path) = await SourcesAsync();
        IFeatureSummaries postgis = (IFeatureSummaries)postgisSource;

        try
        {
            Polygon area = new(new LinearRing(XySequence.Wrap(
                [3_000_000, 4_400_000, 3_900_000, 4_450_000, 3_700_000, 4_900_000, 3_050_000, 4_700_000, 3_000_000, 4_400_000])));

            FeatureQuery[] queries =
            [
                new(1, spatial: new SpatialFilter(area), where: Where("score <> 2")),
                new(1, boundingBox: new Envelope(3_100_000, 4_500_000, 3_600_000, 4_800_000), outSrid: 4326),
                new(1),
            ];

            foreach (FeatureQuery query in queries)
            {
                IReadOnlyList<long> expectedIds = await postgis.ObjectIdsAsync(query, CancellationToken.None);
                IReadOnlyList<long> actualIds = await parquet.ObjectIdsAsync(query, CancellationToken.None);
                Assert.Equal(expectedIds, actualIds);

                (Envelope? expectedExtent, long expectedCount) = await postgis.ExtentAsync(query, CancellationToken.None);
                (Envelope? actualExtent, long actualCount) = await parquet.ExtentAsync(query, CancellationToken.None);

                Assert.Equal(expectedCount, actualCount);
                Assert.NotNull(actualExtent);

                // PostGIS's extent is at most a single-precision step wider, and never narrower.
                Envelope e = expectedExtent!.Value, a = actualExtent.Value;
                Assert.True(
                    e.MinX <= a.MinX && e.MinY <= a.MinY && e.MaxX >= a.MaxX && e.MaxY >= a.MaxY
                    && Near(e.MinX, a.MinX, 4e-7) && Near(e.MinY, a.MinY, 4e-7) && Near(e.MaxX, a.MaxX, 4e-7) && Near(e.MaxY, a.MaxY, 4e-7),
                    $"PostGIS {e}, GeoParquet {a}.");
            }

            FeatureQuery statistics = new(
                10,
                groupBy: ["kind"],
                where: Where("objectid <= 1200"),
                spatial: new SpatialFilter(area),
                statistics:
                [
                    new StatisticRequest(StatisticKind.Count, "objectid", "n"),
                    new StatisticRequest(StatisticKind.Sum, "area", "total"),
                    new StatisticRequest(StatisticKind.Avg, "area", "mean"),
                    new StatisticRequest(StatisticKind.Min, "day", "first"),
                    new StatisticRequest(StatisticKind.Max, "score", "top"),
                    new StatisticRequest(StatisticKind.StdDev, "area", "sd"),
                    new StatisticRequest(StatisticKind.PercentileContinuous, "area", "median", 0.5),
                    new StatisticRequest(StatisticKind.PercentileDiscrete, "score", "p90", 0.9),
                ]);

            IReadOnlyList<IReadOnlyDictionary<string, object?>> expectedRows = await postgis.StatisticsAsync(statistics, CancellationToken.None);
            IReadOnlyList<IReadOnlyDictionary<string, object?>> actualRows = await parquet.StatisticsAsync(statistics, CancellationToken.None);

            Assert.Equal(3, expectedRows.Count);
            Assert.Equal(expectedRows.Count, actualRows.Count);

            for (int i = 0; i < expectedRows.Count; i++)
            {
                foreach ((string name, object? value) in expectedRows[i])
                {
                    object? expected = Comparable(value), actual = Comparable(actualRows[i][name]);

                    Assert.True(
                        expected is double x && actual is double y ? Near(x, y, 1e-9) : Equals(expected, actual),
                        $"{name} of group {i}: PostGIS {expected}, GeoParquet {actual}.");
                }
            }
        }
        finally
        {
            folder.Dispose();
            Directory.Delete(path, recursive: true);
        }
    }

    private static bool Near(double a, double b, double relative) =>
        Math.Abs(a - b) <= (Math.Max(Math.Abs(a), Math.Abs(b)) * relative) + 1e-12;

    /// <summary>A value in the one shape both providers can be compared in.</summary>
    private static object? Comparable(object? value) => value switch
    {
        null => null,
        int or long or short => Convert.ToInt64(value, CultureInfo.InvariantCulture),
        float or double or decimal => Convert.ToDouble(value, CultureInfo.InvariantCulture),
        DateTime moment => DateTime.SpecifyKind(moment, DateTimeKind.Unspecified),
        _ => value,
    };
}
