<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GisServer.Security.Argon2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GisServer.Platform\GisServer.Platform.csproj" />
  </ItemGroup>

</Project>
