<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GisServer.Api.ArcGis.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GisServer.Api.ArcGis\GisServer.Api.ArcGis.csproj" />
  </ItemGroup>

</Project>
