# The environment that produces the checked-in glyph ranges, pinned so anybody can reproduce
# them.
#
# <b>[D-193](../docs/architecture-debt.md).</b> The ranges under `src/Graticula.Host/glyphs`
# are generated by `tools/make-glyphs.py`, and on 2026-08-27 regenerating them on Linux
# produced different bytes for **22 of 31** — some the same size with a different hash, some a
# different size entirely, meaning a different set of glyphs was rasterised at all. The
# rasteriser is Pillow's, Pillow's is FreeType's, and neither promises identical output across
# versions or platforms. So *regenerate and compare* — the only check that proves the files are
# the generator's output rather than merely unedited — meant something on the author's machine
# and nowhere else, and a contributor who regenerated got 22 changed files with no way to tell
# a real change from their FreeType.
#
# <b>Quantising the distance field was the cheaper route and it cannot work.</b> It would
# absorb small rasteriser differences, and the differences measured were not small: a range
# changing size means glyphs present in one build and absent in the other, which no rounding
# reconciles.
#
# <b>A container in the tooling path, not in the deployment path.</b> This project's deployment
# story is one binary and PostGIS, and that is unchanged: nothing here ships. `make-glyphs.py`
# already needs numpy, Pillow and scipy, none of which the server has ever carried. What this
# adds is that the three have versions, and so does FreeType underneath them.
#
# Usage:
#   docker build -f tools/glyphs.Dockerfile -t graticula-glyphs:pinned tools
#   docker run --rm -v "$PWD:/repo" graticula-glyphs:pinned \
#          python /repo/tools/make-glyphs.py /repo/src/Graticula.Host/glyphs
#
# <b>The base image is pinned by digest, because a tag moves.</b> `python:3.12-slim` today is
# not `python:3.12-slim` next month, and a floating base defeats the whole point of this file:
# the FreeType that matters is the one in the image, and it changes with the image.
FROM python@sha256:7a8b475003c4fe15a2cd4e55e5cfc2f3560bdc9333d624f24cdd6d4340fd7a17

# Pinned to what produced the ranges recorded in `src/Graticula.Host/glyphs/provenance.json`.
# Changing any of these changes the bytes, which `tools/glyphs-check.py` will say out loud.
RUN pip install --no-cache-dir \
        numpy==1.26.4 \
        pillow==12.2.0 \
        scipy==1.15.3

WORKDIR /repo
