#!/usr/bin/env python3
"""Builds signed-distance-field glyph ranges for the vector tile style.

Why this exists
---------------
A MapLibre or Mapbox GL style that sets `text-field` cannot render a single
label without a `glyphs` URL, and the URL must serve signed-distance-field
bitmaps in Mapbox's glyph protobuf. Our VectorTileServer served a style with no
`glyphs` key at all, so the tile service could not put a name on a map — which
is most of what anybody wants vector tiles for.

Why it is a build-time tool and not runtime code
------------------------------------------------
Q-15 requires air-gapped operation: nothing fetched at runtime, ever. That rules
out pointing the style at a public glyph server, and it means the glyphs have to
be in the image. Producing them needs a font rasteriser and a distance
transform; doing that at runtime would put a font stack on the request path to
compute something that never changes. So the ranges are generated once, checked
in, and served as files.

The output is data, not code. It is regenerated by running this, and the
generator is the specification.

Format
------
Mapbox's `glyphs.proto`, which is small enough to write by hand:

    message glyph    { uint32 id=1; bytes bitmap=2; uint32 width=3;
                       uint32 height=4; sint32 left=5; sint32 top=6;
                       uint32 advance=7; }
    message fontstack{ string name=1; string range=2; repeated glyph glyphs=3; }
    message glyphs   { repeated fontstack stacks=1; }

`width` and `height` are the glyph without its buffer; the bitmap is
`(width+6) x (height+6)`, because every glyph carries a three-pixel border so
the distance field survives to the edge. Clients rely on that arithmetic
exactly, so it is asserted rather than assumed.

The distance field follows tiny-sdf: radius 8, cutoff 0.25, so the glyph edge
lands on alpha 191 and a client thresholding at 192 gets the outline back.

Usage:  python tools/make-glyphs.py [output-directory]
"""

import io
import os
import sys

import numpy as np
from PIL import ImageFont
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The size every glyph is rasterised at. Not a rendering choice — it is the size
# the format assumes, and a client scales the field rather than asking for
# another one.
SIZE = 24

# Three pixels of border on every side. The number is the client's, not ours.
BUFFER = 3

# tiny-sdf's defaults, and clients threshold at 192 expecting them.
RADIUS = 8.0
CUTOFF = 0.25

# <b>Rasterised once, at the size the format is defined at, and the edge lands
# on a whole pixel.</b> Measured against an eight-times reference the edge is
# half a pixel out on average and two pixels at worst, which is what a client
# magnifies when it draws text far above the design size.
#
# <b>Supersampling was tried on 2026-08-15 and made it worse, which is why the
# simple version is here.</b> Rasterising at six times and sampling the field
# back down should have placed the edge within a sixth of a pixel. It did not:
# FreeType grid-fits each size separately, so a 144-pixel outline is not a
# 24-pixel one scaled — stems land differently — and reconstruction against the
# font's own 24-pixel rasterisation fell from 1.000 to 0.820. The fine shape was
# measured more precisely and it was a measurement of a different shape.
#
# Doing it properly needs a rasteriser that can be told not to hint, which PIL
# does not expose. Recorded rather than left for somebody to rediscover.

# <b>Which ranges get built.</b> Latin, Latin Extended-A and -B carry Turkish —
# the audience this product is for — plus the punctuation and symbol blocks a
# label actually uses. Greek and Cyrillic are cheap and DejaVu has them. The
# whole of the Basic Multilingual Plane would be 256 ranges and mostly empty for
# this font; a range with no glyphs in it is not written at all, so the cost of
# being generous here is only the cost of checking.
BLOCKS = [
    (0x0000, 0x0FFF),  # Latin, Latin-1, Extended-A/B, IPA, Greek, Cyrillic, Hebrew, Arabic
    (0x1E00, 0x1FFF),  # Latin Extended Additional, Greek Extended
    (0x2000, 0x2BFF),  # punctuation, currency, arrows, maths, geometric shapes
    (0xFB00, 0xFB4F),  # ligatures
]


def varint(value):
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        out.append(byte | (0x80 if value else 0))
        if not value:
            return bytes(out)


def tag(field, wire):
    return varint((field << 3) | wire)


def field_varint(number, value):
    return tag(number, 0) + varint(value)


def field_zigzag(number, value):
    return tag(number, 0) + varint((value << 1) ^ (value >> 31))


def field_bytes(number, value):
    return tag(number, 2) + varint(len(value)) + value


def signed_distance(inside):
    """Pixels to the edge: negative within the shape, positive outside it."""
    return (ndimage.distance_transform_edt(~inside)
            - ndimage.distance_transform_edt(inside))


def to_alpha(signed):
    """tiny-sdf's mapping, which puts the edge on 191 and the client's 192."""
    alpha = 255.0 - 255.0 * (signed / RADIUS + CUTOFF)
    return np.clip(np.rint(alpha), 0, 255).astype(np.uint8)


def glyph(font, ascent, code):
    """One glyph, or None when the font has nothing at this codepoint."""
    character = chr(code)

    if font.getmask(character).size == (0, 0):
        # No ink. A space still needs its advance, or every label collapses.
        advance = int(round(font.getlength(character)))
        return None if advance == 0 else (code, b"", 0, 0, 0, 0, advance)

    mask, (left, top_from_ascender) = font.getmask2(character, mode="L")
    width, height = mask.size

    if width == 0 or height == 0:
        return None

    bitmap = np.frombuffer(bytes(mask), dtype=np.uint8).reshape(height, width) > 127

    # Padded before the transform, so the field is real out to the buffer
    # instead of measuring the distance to the edge of the canvas.
    padded = np.zeros((height + 2 * BUFFER, width + 2 * BUFFER), dtype=bool)
    padded[BUFFER:BUFFER + height, BUFFER:BUFFER + width] = bitmap

    field = to_alpha(signed_distance(padded))

    # FreeType's bitmap_top: how far the top of the glyph sits above the
    # baseline. PIL reports the offset down from the ascender instead, so this
    # is the conversion, and getting it wrong drops every label by an ascender.
    top = ascent - top_from_ascender

    advance = int(round(font.getlength(character)))

    return (code, field.tobytes(), width, height, left, top, advance)


def encode(name, start, end, glyphs):
    body = bytearray()
    body += field_bytes(1, name.encode("utf-8"))
    body += field_bytes(2, f"{start}-{end}".encode("ascii"))

    for code, bitmap, width, height, left, top, advance in glyphs:
        one = bytearray()
        one += field_varint(1, code)

        if bitmap:
            one += field_bytes(2, bitmap)

        one += field_varint(3, width)
        one += field_varint(4, height)
        one += field_zigzag(5, left)
        one += field_zigzag(6, top)
        one += field_varint(7, advance)

        body += field_bytes(3, bytes(one))

    return field_bytes(1, bytes(body))


def codepoints():
    for first, last in BLOCKS:
        for start in range(first, last + 1, 256):
            yield start, min(start + 255, last)


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        ROOT, "src", "Graticula.Host", "glyphs")

    source = sys.argv[2] if len(sys.argv) > 2 else FONT

    name = "DejaVu Sans Regular"
    folder = os.path.join(target, name)
    os.makedirs(folder, exist_ok=True)

    font = ImageFont.truetype(source, SIZE)
    ascent, _ = font.getmetrics()

    written = 0
    total = 0

    for start, end in codepoints():
        found = [g for g in (glyph(font, ascent, c) for c in range(start, end + 1))
                 if g is not None]

        if not found:
            continue

        # The client's arithmetic, asserted here rather than trusted. A bitmap
        # that is not exactly (width+6)(height+6) renders as garbage, and the
        # failure is silent and looks like a font problem.
        for _, bitmap, width, height, _, _, _ in found:
            if bitmap:
                assert len(bitmap) == (width + 2 * BUFFER) * (height + 2 * BUFFER), \
                    f"bitmap is not (width+{2 * BUFFER})x(height+{2 * BUFFER})"

        blob = encode(name, start, end, found)
        path = os.path.join(folder, f"{start}-{end}.pbf")
        io.open(path, "wb").write(blob)

        written += 1
        total += len(blob)

    print(f"{written} ranges, {total / 1024:.0f} KB, into {folder}")


FONT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "fonts", "DejaVuSans.ttf")

if __name__ == "__main__":
    main()
