#!/usr/bin/env python3
"""Builds signed-distance-field glyph ranges for the vector tile style.

Why this exists
---------------
A MapLibre or Mapbox GL style that sets `text-field` cannot render a single
label without a `glyphs` URL, and the URL must serve signed-distance-field
bitmaps in Mapbox's glyph protobuf. Our VectorTileServer served a style with no
`glyphs` key at all, so the tile service could not put a name on a map — which
is most of what anybody wants vector tiles for.

Why it is a build-time tool and not runtime code
------------------------------------------------
Q-15 requires air-gapped operation: nothing fetched at runtime, ever. That rules
out pointing the style at a public glyph server, and it means the glyphs have to
be in the image. Producing them needs a font rasteriser and a distance
transform; doing that at runtime would put a font stack on the request path to
compute something that never changes. So the ranges are generated once, checked
in, and served as files.

The output is data, not code. It is regenerated by running this, and the
generator is the specification.

One stack, several fonts — ADR-100
----------------------------------
The served stack is still called `DejaVu Sans Regular`, because that is the name
every stored style already asks for, and it is now a **composite**: each
codepoint's glyph comes from the first font in `tools/fonts/stack.json` whose
`cmap` has it, so DejaVu answers everything it answered before and the Noto
families fill in the scripts it does not have. The one exception is a script
font's own blocks, where that font answers first — `STACK_FILE` says why.

Noto Sans CJK is not in the default build: it is `--cjk`, and ADR-100 §4 carries
the measurement that decided that.

Needs numpy, Pillow, scipy and fontTools, at the versions `tools/glyphs.Dockerfile`
pins.

Format
------
Mapbox's `glyphs.proto`, which is small enough to write by hand:

    message glyph    { uint32 id=1; bytes bitmap=2; uint32 width=3;
                       uint32 height=4; sint32 left=5; sint32 top=6;
                       uint32 advance=7; }
    message fontstack{ string name=1; string range=2; repeated glyph glyphs=3; }
    message glyphs   { repeated fontstack stacks=1; }

`width` and `height` are the glyph without its buffer; the bitmap is
`(width+6) x (height+6)`, because every glyph carries a three-pixel border so
the distance field survives to the edge. Clients rely on that arithmetic
exactly, so it is asserted rather than assumed.

The distance field follows tiny-sdf: radius 8, cutoff 0.25, so the glyph edge
lands on alpha 191 and a client thresholding at 192 gets the outline back.

Usage:  python tools/make-glyphs.py [output-directory] [--cjk]
"""

import hashlib
import io
import json
import os
import platform
import sys
import urllib.request

import numpy as np
import PIL
import scipy
from fontTools.ttLib import TTFont
from PIL import ImageFont
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts")

# The name of the stack this writes, which is the name stored styles already use.
NAME = "DejaVu Sans Regular"

# The size every glyph is rasterised at. Not a rendering choice — it is the size
# the format assumes, and a client scales the field rather than asking for
# another one.
SIZE = 24

# Three pixels of border on every side. The number is the client's, not ours.
BUFFER = 3

# tiny-sdf's defaults, and clients threshold at 192 expecting them.
RADIUS = 8.0
CUTOFF = 0.25

# <b>Rasterised once, at the size the format is defined at, and the edge lands
# on a whole pixel.</b> Measured against an eight-times reference the edge is
# half a pixel out on average and two pixels at worst, which is what a client
# magnifies when it draws text far above the design size.
#
# <b>Supersampling was tried on 2026-08-15 and made it worse, which is why the
# simple version is here.</b> Rasterising at six times and sampling the field
# back down should have placed the edge within a sixth of a pixel. It did not:
# FreeType grid-fits each size separately, so a 144-pixel outline is not a
# 24-pixel one scaled — stems land differently — and reconstruction against the
# font's own 24-pixel rasterisation fell from 1.000 to 0.820. The fine shape was
# measured more precisely and it was a measurement of a different shape.
#
# Doing it properly needs a rasteriser that can be told not to hint, which PIL
# does not expose. Recorded rather than left for somebody to rediscover.

# <b>The stack lives in `tools/fonts/stack.json`, in order, with each font's SHA-256 —
# ADR-100.</b> One file, because the raster face draws its labels from the same list: two
# copies of *which font answers which codepoint* would be two answers the day somebody edits
# one. A font whose bytes are not the pinned ones is refused before anything is drawn from
# it, because the ranges are only reproducible from the files they were made from, and a
# font upgraded in place would change thousands of glyphs with nothing saying why.
#
# <b>DejaVu first, so nothing it drew before changes.</b> Every Latin, Greek and Cyrillic
# glyph a stored style has been drawing since ADR-027 comes out of this byte for byte —
# `GlyphCompositeTests` holds that to a digest taken from the ranges before this change.
# Noto Sans second fills the Latin, Greek and Cyrillic DejaVu lacks, in a face close enough
# not to jar beside it.
#
# <b>A script font answers first in the blocks it claims, which is the one place DejaVu
# does not lead.</b> DejaVu has 165 of the 256 Arabic codepoints, 54 of Hebrew's 112 and
# most of Armenian and Georgian, drawn in its own style. First-font-wins for each codepoint
# would have made an Arabic word out of two typefaces whose joining strokes do not meet — a
# word whose letters come from different designs is not a word anybody reads comfortably.
# So within the blocks a script font claims, it is asked first, and DejaVu is asked only
# for what that font lacks. Nothing in those blocks was ever promised: the README said
# *Latin, Greek and Cyrillic only*. INFERRED from the owner's rule, which named DejaVu
# first *so that Latin, Greek and Cyrillic stay byte-identical* — ADR-100 lists it for
# confirmation. The Arabic claim includes the presentation forms, because they are what
# MapLibre's RTL plugin turns Arabic into before it asks for glyphs.
#
# <b>Noto Sans CJK is the one `optional` font — ADR-100 §4.</b> 16 MB of font and 36 MB of
# ranges, more than every other glyph in the image together, for scripts most deployments
# of this product never label in. It is not checked in: `--cjk` fetches it from the pinned
# tag at build time and refuses it unless its hash matches, so a build that adds it is as
# reproducible as one that does not. **The SC file, because it is the one file set that
# covers all four**: it carries every Han ideograph, kana and Hangul syllable the regional
# files do, and what differs between them is which *form* of a unified ideograph is the
# default. Simplified Chinese forms are therefore what a Japanese, Korean or Traditional
# Chinese label gets where the regions differ — INFERRED as acceptable, ADR-100.
STACK_FILE = os.path.join(FONTS, "stack.json")


def claims(entry):
    """`0600-06FF` strings as (first, last) integer pairs."""
    return [tuple(int(end, 16) for end in block.split("-")) for block in entry["claims"]]


def skipped(code):
    """Codepoints no label draws and no range should answer for.

    Controls are not glyphs, surrogates are not characters, private use means
    whatever one font decided, and a noncharacter is by definition nothing. Before
    ADR-100 this rested on whether PIL drew ink — and PIL draws a box for a
    codepoint the font does not have, so the old ranges served 3,800 boxes as
    glyphs, the C0 controls among them.
    """
    return (code < 0x20 or 0x7F <= code <= 0x9F or 0xD800 <= code <= 0xF8FF
            or 0xFDD0 <= code <= 0xFDEF or code >= 0xFFFE)


def varint(value):
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        out.append(byte | (0x80 if value else 0))
        if not value:
            return bytes(out)


def tag(field, wire):
    return varint((field << 3) | wire)


def field_varint(number, value):
    return tag(number, 0) + varint(value)


def field_zigzag(number, value):
    return tag(number, 0) + varint((value << 1) ^ (value >> 31))


def field_bytes(number, value):
    return tag(number, 2) + varint(len(value)) + value


def signed_distance(inside):
    """Pixels to the edge: negative within the shape, positive outside it."""
    return (ndimage.distance_transform_edt(~inside)
            - ndimage.distance_transform_edt(inside))


def to_alpha(signed):
    """tiny-sdf's mapping, which puts the edge on 191 and the client's 192."""
    alpha = 255.0 - 255.0 * (signed / RADIUS + CUTOFF)
    return np.clip(np.rint(alpha), 0, 255).astype(np.uint8)


def glyph(font, ascent, code):
    """One glyph, or None when the font has nothing to draw at this codepoint."""
    character = chr(code)

    # <b>No ink. A space still needs its advance, or every label collapses</b> — and until
    # ADR-100 no space had one. This asked for a mask of size (0, 0), and Pillow gives a space
    # a mask as wide as its advance and zero pixels high, so the test never matched, the next
    # one threw the glyph away for its zero height, and U+0020 was missing from every range
    # this tool has written. A client with no glyph for a codepoint has no advance for it, and
    # MapLibre's shaper skips such a codepoint, so "İstanbul Büyükşehir" would run together —
    # INFERRED from the shaper rather than seen on a map, ADR-100 §4. Either dimension being
    # zero is no ink.
    width, height = font.getmask(character).size

    if width == 0 or height == 0:
        advance = int(round(font.getlength(character)))
        return None if advance == 0 else (code, b"", 0, 0, 0, 0, advance)

    mask, (left, top_from_ascender) = font.getmask2(character, mode="L")
    width, height = mask.size

    if width == 0 or height == 0:
        return None

    bitmap = np.frombuffer(bytes(mask), dtype=np.uint8).reshape(height, width) > 127

    # Padded before the transform, so the field is real out to the buffer
    # instead of measuring the distance to the edge of the canvas.
    padded = np.zeros((height + 2 * BUFFER, width + 2 * BUFFER), dtype=bool)
    padded[BUFFER:BUFFER + height, BUFFER:BUFFER + width] = bitmap

    field = to_alpha(signed_distance(padded))

    # FreeType's bitmap_top: how far the top of the glyph sits above the
    # baseline. PIL reports the offset down from the ascender instead, so this
    # is the conversion, and getting it wrong drops every label by an ascender.
    # Each font's own ascent, since ADR-100: the stack mixes fonts whose ascenders
    # differ, and the baseline is the one thing they share.
    top = ascent - top_from_ascender

    advance = int(round(font.getlength(character)))

    return (code, field.tobytes(), width, height, left, top, advance)


def encode(name, start, end, glyphs):
    body = bytearray()
    body += field_bytes(1, name.encode("utf-8"))
    body += field_bytes(2, f"{start}-{end}".encode("ascii"))

    for code, bitmap, width, height, left, top, advance in glyphs:
        one = bytearray()
        one += field_varint(1, code)

        if bitmap:
            one += field_bytes(2, bitmap)

        one += field_varint(3, width)
        one += field_varint(4, height)
        one += field_zigzag(5, left)
        one += field_zigzag(6, top)
        one += field_varint(7, advance)

        body += field_bytes(3, bytes(one))

    return field_bytes(1, bytes(body))


def digest(path):
    with io.open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def fetch(entry, path):
    """The CJK font, from its pinned tag, at build time — never at runtime (Q-15)."""
    print(f"fetching {entry['file']} from {entry['source']}")
    partial = path + ".partial"

    with urllib.request.urlopen(entry["source"], timeout=300) as response, \
            io.open(partial, "wb") as out:
        while True:
            chunk = response.read(1 << 20)
            if not chunk:
                break
            out.write(chunk)

    os.replace(partial, path)


def load(entry, allow_fetch=False):
    """Opens one font of the stack, refusing it unless its bytes are the pinned ones."""
    path = os.path.join(FONTS, entry["file"])

    if not os.path.exists(path) and allow_fetch:
        fetch(entry, path)

    if not os.path.exists(path):
        sys.exit(f"{entry['file']} is not in tools/fonts. It is part of the pinned stack "
                 "(tools/fonts/stack.json, ADR-100), so the ranges cannot be made without it.")

    actual = digest(path)

    if actual != entry["sha256"]:
        sys.exit(f"{entry['file']} is not the pinned file: SHA-256 {actual}, expected "
                 f"{entry['sha256']}. A different version would change the glyphs with "
                 "nothing saying why; pin the new one in tools/fonts/stack.json deliberately.")

    # BASIC layout, named rather than left to whichever engine this Pillow found. One
    # codepoint at a time has nothing to shape, and a build with libraqm must not draw
    # a single glyph differently from one without it.
    font = ImageFont.truetype(path, SIZE, layout_engine=ImageFont.Layout.BASIC)
    ascent, _ = font.getmetrics()
    cmap = set(TTFont(path, lazy=True).getBestCmap() or {})

    return {"file": entry["file"], "sha256": actual, "font": font, "ascent": ascent,
            "cmap": cmap, "claims": claims(entry)}


def source(stack, code):
    """The font this codepoint is drawn from, or None when no font in the stack has it."""
    for font in stack:
        if code in font["cmap"] and any(a <= code <= b for a, b in font["claims"]):
            return font

    for font in stack:
        if code in font["cmap"]:
            return font

    return None


def runs(codes):
    """Sorted codepoints as `0041-005A` runs, which is how provenance lists them."""
    out = []
    for code in codes:
        if out and out[-1][1] == code - 1:
            out[-1][1] = code
        else:
            out.append([code, code])
    return [f"{first:04X}-{last:04X}" for first, last in out]


def main():
    arguments = [a for a in sys.argv[1:] if not a.startswith("--")]
    cjk = "--cjk" in sys.argv[1:]

    target = arguments[0] if arguments else os.path.join(ROOT, "src", "Graticula.Host", "glyphs")

    with io.open(STACK_FILE, encoding="utf-8") as handle:
        entries = json.load(handle)["fonts"]

    # The optional font keeps its place in the list, which is last. Asked for and missing,
    # it is fetched; not asked for, it is not read even when it is on disk.
    stack = [load(entry, allow_fetch=True) for entry in entries
             if cjk or not entry.get("optional")]

    folder = os.path.join(target, NAME)
    os.makedirs(folder, exist_ok=True)

    # A stale range from an earlier build would still be served, so the folder holds what
    # this run wrote and nothing else.
    for entry in os.listdir(folder):
        if entry.endswith(".pbf"):
            os.remove(os.path.join(folder, entry))

    written = 0
    total = 0
    drawn = {font["file"]: [] for font in stack}

    # <b>Every 256-codepoint range of the Basic Multilingual Plane, on the grid.</b> The
    # block list this replaced wrote `64256-64335.pbf` for the ligatures: a range a client
    # cannot name, because clients only ever ask for `start-(start+255)`, so the file was
    # built, shipped and never served. Walking the grid makes that impossible, and a range
    # none of the fonts reaches is still not written — which is what keeps a client from
    # being handed Latin for Japanese.
    for start in range(0, 0x10000, 256):
        end = start + 255
        found = []

        for code in range(start, end + 1):
            if skipped(code):
                continue

            font = source(stack, code)

            if font is None:
                continue

            one = glyph(font["font"], font["ascent"], code)

            if one is not None:
                found.append(one)
                drawn[font["file"]].append(code)

        if not found:
            continue

        # The client's arithmetic, asserted here rather than trusted. A bitmap
        # that is not exactly (width+6)(height+6) renders as garbage, and the
        # failure is silent and looks like a font problem.
        for _, bitmap, width, height, _, _, _ in found:
            if bitmap:
                assert len(bitmap) == (width + 2 * BUFFER) * (height + 2 * BUFFER), \
                    f"bitmap is not (width+{2 * BUFFER})x(height+{2 * BUFFER})"

        blob = encode(NAME, start, end, found)
        path = os.path.join(folder, f"{start}-{end}.pbf")
        io.open(path, "wb").write(blob)

        written += 1
        total += len(blob)

    # <b>The output records what produced it -- ADR-027 condition 3.</b> Measured 2026-08-27:
    # regenerating on Linux produced different bytes for 22 of 31 ranges, some the same size
    # with a different hash and some a different size entirely, because the rasteriser is
    # Pillow's and Pillow's is FreeType's and neither promises identical output across
    # versions or platforms. So "regenerate and compare" is a check that only means something
    # where the environment matches -- and until the environment was written down, nobody
    # could tell whether a difference was drift or a different machine.
    #
    # <b>The per-file hashes are the half that is portable.</b> They catch a range edited by
    # hand, a range that went missing and a range nobody committed, anywhere, without needing
    # to run this at all.
    #
    # <b>And which font drew which codepoints, since ADR-100.</b> A composite that says only
    # *these bytes* cannot be asked where a glyph came from; `sources` answers it, and
    # `GlyphCompositeTests` asks.
    provenance = {
        "generator": os.path.basename(__file__),
        "stack": NAME,
        "cjk": cjk,
        "fonts": {font["file"]: font["sha256"] for font in stack},
        "environment": {
            "python": platform.python_version(),
            "system": platform.system(),
            "pillow": PIL.__version__,
            "freetype": ImageFont.core.freetype2_version,
            "numpy": np.__version__,
            "scipy": scipy.__version__,
        },
        "sources": {name: runs(codes) for name, codes in drawn.items()},
        "ranges": {},
    }

    for entry in sorted(os.listdir(folder)):
        if entry.endswith(".pbf"):
            provenance["ranges"][entry] = digest(os.path.join(folder, entry))

    io.open(os.path.join(target, "provenance.json"), "w", encoding="utf-8", newline="\n").write(
        json.dumps(provenance, indent=1, sort_keys=True) + "\n")

    print(f"{written} ranges, {total / 1024:.0f} KB, into {folder}")

    for font in stack:
        print(f"  {font['file']}: {len(drawn[font['file']])} glyphs")


if __name__ == "__main__":
    main()
